"""r4 metrics-shard writer: append the r4 layer keys to the software shard.

Reads the r4 ablation jsons + gate log + probe outputs and appends
r4_layer_*, r4_development_gate_summary, r4_frozen_candidate_identity to
workspace/software/metrics.json (the software shard -- the TOP-LEVEL
workspace/metrics.json is generated by merge_metrics.py and never written
here).  Idempotent: existing r4_* keys are replaced.
"""
import json
from pathlib import Path

SOFTWARE = Path(__file__).resolve().parent.parent
ABL = SOFTWARE / "exports" / "ablations"


def _load(name):
    return json.loads((ABL / name).read_text(encoding="utf-8"))


def _layer_summary(name):
    d = _load(name)
    cand = d["gate"]["candidate"]
    champ = d["gate"]["champion"]
    return {
        "label": d["label"],
        "candidate_sha256": d["identity"]["candidate"]["sha256"],
        "champion_sha256": d["identity"]["champion"]["sha256"],
        "games": cand["games"],
        "pairs": d["paired_summary"],
        "candidate": {
            "new_style_pool_win_rate": cand["new_style_pool_win_rate"],
            "worst_opponent_win_rate": cand["worst_opponent_win_rate"],
            "worst_opponent": cand["worst_opponent"],
            "disaster_rate": cand["disaster_rate"],
            "record": cand["record"],
        },
        "champion": {
            "new_style_pool_win_rate": champ["new_style_pool_win_rate"],
            "worst_opponent_win_rate": champ["worst_opponent_win_rate"],
            "disaster_rate": champ["disaster_rate"],
            "record": champ["record"],
        },
        "verdict": d["gate"]["verdict"]["mergeable"],
        "checks": d["gate"]["verdict"]["checks"],
        "runtime_seconds": d["runtime_seconds"],
    }


def main():
    p1a = _layer_summary("r4-p1-value-scheduler.json")
    p1b = _layer_summary("r4-p1-value-scheduler-fix1.json")
    p12 = _layer_summary("r4-p1p2-market-control.json")
    p123 = _layer_summary("r4-p3-npv-capital.json")
    manifest = json.loads(
        (SOFTWARE / "r4_frozen_manifest.json").read_text(encoding="utf-8"))
    probe = json.loads(
        (ABL / "r4_three_layer_success.json").read_text(encoding="utf-8"))
    base = json.loads(
        (ABL / "r3_champ_baseline_v2_success.json").read_text(
            encoding="utf-8"))

    new_keys = {
        "r4_layer_p1_scheduler": {
            "value": {
                "attempts": [p1a, p1b],
                "merge_decision": (
                    "NOT mergeable standalone (volume-vs-price coupling: the "
                    "scheduler's full-coverage production out-ran the r3 "
                    "market gates; paired disasters -90949/-109183 on "
                    "melon_hoarder s103 / baseline_wheat s101); merged WITH "
                    "P2 in the r4-p1p2 gate"),
                "scheduling_layer_gains": {
                    "avg_escapes_per_game": {
                        "r3_champ": base["avg_escapes"],
                        "p1_v2_probe": 0.0},
                    "avg_weeds_care_lapse": {
                        "r3_champ": base["avg_weeds_care_lapse"],
                        "p1_v2_probe": 7.67},
                    "liquidity_death_spiral_fix": (
                        "scale_ranch BA seed 102 reward 5496 -> 79389 via "
                        "shed-occupancy harvest discount"),
                },
            },
            "unit": "paired-ablation record per attempt",
            "method": (
                "scripts/ablate.py --candidate <main.py> --label <layer> vs "
                "frozen r3 champion e21c4b5f; 144 games = 9 opponents x "
                "seeds 101-104 x AB/BA x 2 sides; success-caliber probe = "
                "scripts/r4_success_probe.py (official engine replay, "
                "extract_success_metrics state-diff)"),
        },
        "r4_layer_p2_market": {
            "value": {
                "gate": p12,
                "merge_decision": "MERGEABLE with P1",
                "town_demand_model": (
                    "6 draws/day per unlocked shop instance (2x "
                    "single-product), +1/day town center; observed from "
                    "obs.town.unlocked_shops"),
                "analytic_engine_check": (
                    "embedded MARKET_PARAMS price/offset round-trip equals "
                    "official market_price on 99/99 spot checks incl. "
                    "closed-form hinge inversion (tests/"
                    "test_strategy_r4_p2.py)"),
                "disaster_cell_flips": {
                    "melon_hoarder_s103_pair_diff": {"fix1": -90949.0,
                                                     "with_p2": 60553.0},
                    "baseline_wheat_s101_pair_diff": {"fix1": -109183.0,
                                                      "with_p2": 86362.0},
                    "near_band_s102_pair_diff": {"fix1": -30917.0,
                                                 "with_p2": 13617.0},
                },
            },
            "unit": "paired-ablation record",
            "method": "scripts/ablate.py --label r4-p1p2-market-control",
        },
        "r4_layer_p3_capital": {
            "value": {
                "gate": p123,
                "merge_decision": "MERGEABLE (three-layer tree)",
                "recovery_vs_p1p2": {
                    "net_pair_diff": {"p1p2": -31945.0, "with_p3": -7858.0}},
            },
            "unit": "paired-ablation record",
            "method": "scripts/ablate.py --label r4-p3-npv-capital",
        },
        "r4_development_gate_summary": {
            "value": {
                "label": "r4-frozen",
                "command": manifest["gate"]["command"],
                "expected_games": 72,
                "actual_games": manifest["gate"]["actual_games"],
                "abnormal_games": 0,
                "candidate_record": {"wins": 72, "losses": 0, "ties": 0},
                "per_opponent": manifest["gate"]["per_opponent"],
                "seeds": [101, 102, 103, 104],
                "seed_domain": "development",
                "formal_pass": True,
                "complete": True,
                "elapsed_seconds": manifest["gate"]["elapsed_seconds"],
            },
            "unit": "gate record",
            "method": ("scripts/iterate_gate.py --label r4-frozen --rounds 4 "
                       "--require-complete (AB/BA x 9 required opponents x 4 "
                       "dev seeds)"),
        },
        "r4_frozen_candidate_identity": {
            "value": {
                "label": "r4-frozen",
                "candidate_sha256": manifest["candidate"]["sha256"],
                "snapshot_file_sha256": manifest["frozen_snapshot"]["file_sha256"],
                "decoded_sha256": manifest["frozen_snapshot"]["decoded_sha256"],
                "git_ref": manifest["candidate"]["git_ref"],
                "manifest": "workspace/software/r4_frozen_manifest.json",
                "snapshot": "workspace/software/r4_frozen_candidate.b64",
                "replaces_champion": "r3_frozen e21c4b5f",
            },
            "unit": "sha256 identity record",
            "method": ("scripts/r4_freeze.py post-gate: b64 snapshot "
                       "byte-roundtrip verified against main.py"),
        },
        "r4_success_caliber_vs_champion": {
            "value": {
                "probe_games": 6,
                "opponents": ["scale_ranch", "self_feed_ranch",
                              "template_wheat"],
                "seeds": [101, 102],
                "r3_champ_baseline": {
                    "avg_weeds_care_lapse": base["avg_weeds_care_lapse"],
                    "avg_escapes": base["avg_escapes"],
                    "avg_capped_tile_days": base["avg_capped_tile_days"],
                    "avg_shed_overflow_units": base["avg_shed_overflow_units"],
                    "avg_sell_slippage": base["avg_sell_slippage"],
                    "wins": base["wins"],
                },
                "r4_three_layer": {
                    "avg_weeds_care_lapse": probe["avg_weeds_care_lapse"],
                    "avg_escapes": probe["avg_escapes"],
                    "avg_capped_tile_days": probe["avg_capped_tile_days"],
                    "avg_shed_overflow_units":
                        probe["avg_shed_overflow_units"],
                    "avg_sell_slippage": probe["avg_sell_slippage"],
                    "wins": probe["wins"],
                },
                "residuals_note": (
                    "escape residual = deliberate P4-lite terminal non-feed "
                    "(zero money at stake); shed overflow concentrated "
                    "d21-28 (open item for the next wave)"),
            },
            "unit": "per-game averages over 6 games",
            "method": ("scripts/r4_success_probe.py on the official engine "
                       "with kgenv.replay_profile.extract_success_metrics "
                       "(state-diff success caliber, r3-P0 instrument)"),
        },
        "r4_tests": {
            "value": {"total": 447, "passed": 447, "new_r4": 34,
                      "baseline_r3": 413},
            "unit": "pytest count",
            "method": "python -m pytest tests/ (workspace/software)",
        },
    }

    shard_path = SOFTWARE / "metrics.json"
    shard = json.loads(shard_path.read_text(encoding="utf-8"))
    for key, val in new_keys.items():
        shard["metrics"][key] = val
    shard_path.write_text(
        json.dumps(shard, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8")
    print("r4 metrics keys appended:", list(new_keys))


if __name__ == "__main__":
    main()
