# NOMEL1: MEL-coded seats get the generic curve (2026-09-30, 15:18-16:15Z). Verdict: NONE, not packaged

**Question.** Live, on P48 seats the h1-cash latch codes MEL, the shipped pair (vrp25 56706557 / vrp26 56707958) is 1-8 (-10.8k). On P48 seats the latch leaves NONE it is 9-3 (REFRESH9 census). Would routing every MEL-coded seat to the curve that NONE seats get (S_OTH) do better? That means never applying the MEL, P48 or PQ4 family curves.

**Answer.** No. On the tapes the family curve helps on MEL-coded seats.
- **HARNESS1 H mode (primary judge):** NOMEL against vrp26 on MEL-coded seats is **-484/game (t -2.54), flips +2 -4** (P48TAPE172, n73). On PQ4TAPE26 (n26) it is **-834 (t -1.85), flips +1 -2**. Pooled over the unique MEL-coded games (n81): **-510 (t -2.57), net flips -2**.
- **G25 gate-reactive (secondary):** +804 (t 0.91), flips +4 -3. The whole gain sits in the rival column (-589): these are the tape-collapse rows HARNESS1 documented. Own is +215, t 0.44.
- **Other seats:** all V56-coded and NONE-coded seats are byte-identical, as designed.

The promotion bar (net flips >= +2 and margin t >= 2 on MEL seats, under the reacting harness) is failed in the wrong direction. LIVEWATCH24's counterfactual reached the same conclusion from the live side: vrp24 also loses all 6 live MEL-latched losses, so the live 1-8 is rival strength, not the curve. The NOMEL_P48ONLY variant was not run: PQ4 has the same sign as P48 (both negative), and the coordinator asked to skip it unless PQ4 came out positive.

## Cell
- **Switch:** `OPP_SUPPLY_MEL_TO_NONE_ON` in `src/kagg3/core/plan.py` plus the `submission/` mirror, default OFF.
  - Branch `nomel1_0930` off master fe602a07 (the vrp26 tree). Commit **01cd97b1**. Worktree /mnt/e/_work/kagg3_wt_nomel1, sparse.
  - When on, `opp_supply_family` returns `"NONE"` for a MEL code. The projector then loads S_OTH, exactly as it does for an off-list rival.
  - V56 codes, NONE codes and step 0 (pop) are unchanged.
- **Variant switch:** `OPP_SUPPLY_MEL_TO_NONE_KEEP_PQ4` gives NOMEL_P48ONLY: MEL before d10, PQ4 on 4 quadrants, only P48 goes to NONE. Built but not read.
- **Judge package:** `/home/user/stage_r/nomel1/pkg/n27` = CONFIRM1's unpacked vrp26 package with only plan.py replaced (md5 89e4119e). `diff` against v26 shows only the switch lines.

## Identity
| check | result |
|---|---|
| OFF (n27, switch off) vs HARNESS1 v26H rows, H mode, first 3 P48 tapes | **3/3 exact**: money, ndiff, first divergence, sales ledger, rival dawn purses |
| ON, non-MEL-coded P48 rows vs vrp26 | **99/99 identical** in H mode and 99/99 in G mode (V56 10, NONE 89) |
| ON, V56 m40 x3 + v21 x3 (local, S/revfix1/rj.py) vs S/stack1 v_hAC / vv_hAC | **6/6 byte-identical**, all 12 money columns |
| Latch codes on the V56 panel | all 61 boards latch V56 (rival h1 cash 2901), so NOMEL is identical on the whole V56 leg by construction |
| ON, OTH56 taped, non-MEL rows | 55/55 identical (V56 5, NONE 50) |

## Rows: NOMEL minus vrp26, split by the shipped latch code of the rival's in-sim h1 cash
Units: straw is our strawberry units sold d15-17; animal is our milk+wool+egg units sold d18-29.

**HARNESS1 H mode (primary; P48 with the G25 wool gate, PQ4 without a gate).** The vrp26 rows are HARNESS1's v26H plus my cH_new23 and cH_pq.

| set | code | n | own (t) | rival (t) | margin (t) | W vrp26 → NOMEL | flips | straw | animal |
|---|---|---|---|---|---|---|---|---|---|
| P48TAPE172 | **MEL** | 73 | -414 (-1.96) | +70 (0.38) | **-484 (-2.54)** | 16 → 14 | **+2 -4** | +1.45 | -3.97 |
| P48TAPE172 | V56 | 10 | 0 | 0 | 0 (10/10 identical) | 3 → 3 | 0 | 0 | 0 |
| P48TAPE172 | NONE | 89 | 0 | 0 | 0 (89/89 identical) | 36 → 36 | 0 | 0 | 0 |
| PQ4TAPE26 | **MEL** | 26 | -194 (-0.52) | +639 (1.63) | **-834 (-1.85)** | 6 → 5 | **+1 -2** | +1.73 | -9.88 |
| pooled unique MEL | MEL | 81 | -376 (-1.90) | | **-510 (-2.57)** | | **+2 -4** | | |

- **Flips on the MEL-coded P48 seats:**
  - Down: 115463615 (h1 2438), 115417256 (2464), 114946281 (992), 114962331 (938).
  - Up: 115271256 (2438), 114939034 (964).
- **By h1 cash:**
  - 938: n33, -515 (t -1.97)
  - 964: n12, +87
  - 2438: n13, -873
  - 2464: n5, -532
  - The rest: 1-2 games each.

**G25 gate-reactive (secondary; same runner in G mode, P48 only).** The vrp26 rows are HARNESS1's v26G plus my cG_new23.

| set | code | n | own (t) | rival (t) | margin (t) | W vrp26 → NOMEL | flips | straw | animal |
|---|---|---|---|---|---|---|---|---|---|
| P48TAPE172 | **MEL** | 73 | +215 (0.44) | -589 (-1.25) | +804 (0.91) | 17 → 18 | +4 -3 | +1.73 | -0.81 |
| P48TAPE172 | V56 / NONE | 10 / 89 | 0 | 0 | 0 (99/99 identical) | 3 / 38 | 0 | 0 | 0 |

**OTH56 taped (T mode).** Latch codes: 1 MEL, 5 V56 and 50 NONE. The one MEL row reads +3,245 with W → W, so no flip.

**Live-control rows (vrp24 = HARNESS1 v24H/v24G, 149 P48 tapes; the 23 new tapes have no vrp24 row).** On the MEL-coded seats:

| judge | vrp26 − vrp24 | NOMEL − vrp24 |
|---|---|---|
| H | +909 (t 3.52), flips +2 -2 | +452 (t 1.62), flips +0 -2 |
| G | +4,058 (t 1.94) | +4,955 (t 2.19), rival-driven |

Under H, vrp26 already beats the live control on the MEL-coded seats (+909), and removing the curve gives back about half of that.

**Apply time.** Per-call act time from the `tp99` column (per-game p99, remote under load 7-12):
- NOMEL: at most 404 ms on H P48, 480 ms on G, 344 ms on PQ4.
- vrp26: 450 ms on the same boards.

This is under the 0.65 s bar, but moot: no package.

## Reading
- **The curve is doing work on latched seats, and the work is our own.** Under H, own falls 414/game without it. We sell more strawberry d15-17 (+1.45 units) but fewer late animal units (-3.97, and -9.9 on PQ4). The P48/PQ4 curve evidently prices the programme's late milk and wool supply correctly and moves our volume.
- **This agrees with RSFIX1's tape read** (TUNE MEL/P48 n15, own +1,466, t 2.45) and with **LIVEWATCH24's live counterfactual** (vrp24 loses the same 6 live MEL-latched games; the curve costs -1,174, t -1.19). The live 1-8 is the MEL-latched rivals being strong seats; the curve is not what loses those games.
- **G25 inverts the sign.** It credits NOMEL through rival drops (-589/game), the same tape-collapse artefact HARNESS1 measured (G25 overstated vrp26 − vrp24 by about 3.4k/game). This is one more case where G and H disagree on the decision. H is the judge.

## Files
- **S/nomel1:**
  - Scripts: `q.sh`, `launch.sh`, `hrun.py` (= HARNESS1 hrun plus an `h1cash` row field; play unchanged), `nsumm.py` (the split tables), `pooled.py`, `detail.py`, `chain.sh` (local V56 identity).
  - Results: `res/nsumm_out.md`, `res/pooled_out.txt`, `res/detail_out.txt`, `res/rows/*.jsonl`, `res/{m40,v21}_n27*`.
  - Logs: `checkpoint.txt`, `slips.txt`.
- **Remote:** `/home/user/stage_r/nomel1`, 4.7 MB. It holds the pkg/n27 judge package, the lists and res.
- **Not touched:** master, the shipped files and dist.

## Slips
1. At 15:23Z a local `cp` carried a stderr redirect to the null device. It was harmless and produced no output, but it breaks the no-/dev rule.
