"""MULTI-CHECKPOINT bandit branch generator (moved into the bandit package
2026-09-19; formerly trackp/harness/multi_checkpoint_evolve.py).

Shops unlock cumulatively every 3 days, so a D6-committed economy cannot adapt
to demand that arrives later. This evolves a NESTED branch at EACH configured
checkpoint (D6/D12/D15/D21/D27), keyed on the CUMULATIVE shop set at that
checkpoint, so the tape re-tilts production as each new shop spawns. Branches
are GENERATED by (1+lambda) evolution on the Rust batch engine vs a strong
panel; the base is only a scaffold whose >=checkpoint economy is overwritten.

Output models/bandit/branches.json:
  { "<day>": { "<shopkey>": {"cont": [...], "score":.., "base":.., "n":..} } }
where <shopkey> = sorted cumulative shops at that checkpoint.

Dependencies: `bandit.scaffold.our_route` (bandit-owned base economy) and the
SHARED measurement infrastructure `pipeline.sell_search` / `engine.serve_match`
plus `build_panel` (opponent panel from the route registry). `build_panel` and
the route-registry/realized-world modules it uses are shared infra still filed
under `trackp/`; relocating them to a neutral package is a separate cleanup.
"""
from __future__ import annotations
from kaggriculture.paths import ROOT
import argparse, copy, json, os, random
from collections import defaultdict

import kaggriculture.pipeline.sell_search as SS          # SHARED infra
import kaggriculture.engine.serve_match as SM            # SHARED infra
from kaggriculture.bandit.scaffold import our_route      # bandit-owned base scaffold
from kaggriculture.bandit.build.build_rust_bandit import parse_tape  # shipped-base loader
from kaggriculture.trackp.harness.day3_evolve import build_panel  # SHARED opponent-panel infra (pending relocation)


def load_base(cfg_path, base_tape_arg=None):
    """Load the base the RUNTIME actually replays: the config's base_tape (the
    shipped base, e.g. v51), NOT the v45 our_route() scaffold. Branches spliced
    onto a prefix that differs from what runtime plays is the mismatch that
    tanks a raw-strong generalist at full-bandit. Falls back to our_route()
    only when no base_tape is configured."""
    bt = base_tape_arg
    if not bt:
        try:
            cfg = json.load(open(cfg_path, encoding="utf-8"))
            bt = cfg.get("base_tape")
        except Exception:
            bt = None
    if bt:
        p = bt if os.path.isabs(bt) else os.path.join(ROOT, bt)
        if os.path.exists(p):
            rows = parse_tape(p)
            print(f"base := shipped base_tape {os.path.relpath(p, ROOT)} "
                  f"({len(rows)} rows)", flush=True)
            return rows[:720]
        print(f"WARNING base_tape {p} missing; falling back to our_route() scaffold",
              flush=True)
    print("base := our_route() v45 scaffold (no base_tape configured)", flush=True)
    return our_route()

WORK = os.path.join(ROOT, ".local", "mck")
# D6 is MANDATORY; D12/D15/D21/D27 are OPTIONAL (configured). Branches NEST, so
# the generator must evolve exactly the configured active set. step = day*24+2.
ALL_CKPTS = {6: 146, 12: 290, 15: 362, 21: 506, 27: 650}
TURNS = 24


def load_checkpoints(cfg_path):
    """Active checkpoints as [(day, step), ...] from config; D6 always included."""
    days = {6}
    if cfg_path and os.path.exists(cfg_path):
        cfg = json.load(open(cfg_path, encoding="utf-8"))
        for c in cfg.get("checkpoints", []):
            days.add(int(c[1]))
    else:
        days |= set(ALL_CKPTS)               # default: full operator schedule
    return [(d, ALL_CKPTS[d]) for d in sorted(days) if d in ALL_CKPTS]


def shopkey(shops, k):
    return "|".join(sorted(shops[:k])) if len(shops) >= 2 else None


def capture(route, panel_tapes, seeds, ckpts):
    """Per cell -> {day: cumulative-shopkey}. One GENGAME/cell on Rust serve.

    Keys are read from the GENGAME `ckpts` array -- full-state snapshots taken at
    the EXACT dispatch phase (day*24+2), the same step mbandit's dispatch()
    reads unlocked_shops -- and matched to each checkpoint by step. The old code
    read `days[min(day,len-1)]`, but `days` is day*24-phased and starts at day 8
    (step 192), so it never contained the D6 step (146) and mis-indexed every
    other checkpoint (days[6] was actually day 14). That is why NO generated key
    ever matched at runtime. shopkey() = sorted(shops[:8]), identical to the Rust
    dispatch key. Requires an isolated kagg built after the ckpts field was added.
    """
    ours = chr(31).join(SM.action_to_line(a) for a in route[:719])
    step_of = {day: step for (day, step) in ckpts}
    srv = SM.Serve(); cell_shops = {}
    try:
        for oi, ot in enumerate(panel_tapes):
            for s in seeds:
                for seat in (0, 1):
                    a, b = (ours, ot) if seat == 0 else (ot, ours)
                    js = srv.cmd("GENGAME " + str(s) + chr(30) + a + chr(30) + b)
                    snaps = js.get("ckpts") or []
                    if not snaps or "error" in js:
                        continue
                    by_step = {}
                    for snap in snaps:
                        st = snap.get("step")
                        sh = ((snap.get("town") or {})
                              .get("unlocked_shops") or [])
                        if st is not None:
                            by_step[int(st)] = sh
                    perday = {}
                    for (day, step) in ckpts:
                        sh = by_step.get(step_of.get(day, step), [])
                        perday[day] = shopkey(sh, min(len(sh), 8))
                    cell_shops[(oi, s, seat)] = perday
    finally:
        srv.close()
    return cell_shops


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gens", type=int, default=8)
    ap.add_argument("--lam", type=int, default=6)
    ap.add_argument("--seeds", type=int, default=90)
    ap.add_argument("--min-cells", type=int, default=6)
    ap.add_argument("--cells", type=int, default=12)
    ap.add_argument("--threads", type=int, default=3)
    ap.add_argument("--config", default=os.path.join(ROOT, "configs", "bandit_config.json"),
                    help="active checkpoints come from this config (D6 always)")
    ap.add_argument("--out", default=os.path.join(
        ROOT, "models", "bandit", "branches.json"))
    ap.add_argument("--base-tape", default=None,
                    help="raw .tape base to evolve branches ON (else config.base_tape, "
                         "else our_route scaffold). MUST match what runtime replays.")
    ap.add_argument("--kagg", default=os.path.join(
        ROOT, "rustengine", ".local", "scratch", "bandit_target", "release", "kagg.exe"),
        help="serve binary for capture -- MUST be a build carrying the GENGAME "
             "`ckpts` field (the isolated bandit build). Defaults to it.")
    a = ap.parse_args()
    if a.kagg and os.path.exists(a.kagg):
        SM.KAGG = a.kagg                       # capture reads exact-step shop keys
        print(f"capture serve binary := {os.path.relpath(a.kagg, ROOT)}", flush=True)
    os.makedirs(WORK, exist_ok=True)
    rng = random.Random(41)
    base = load_base(a.config, a.base_tape)  # the SHIPPED base (v51), not v45 scaffold
    panel = build_panel()
    panel_tapes = [chr(31).join(open(p, encoding="utf-8").read().splitlines()[
        (1 if open(p, encoding="utf-8").readline().startswith("SEED") else 0):])
        for p in panel]
    bank = json.load(open(os.path.join(ROOT, "data", "worlds",
                                       "seed_bank.json"), encoding="utf-8"))
    # seed_bank format (2026-09): {"seeds":[...], "worlds_covered":int, "by_world":{...}}.
    # Prefer the flat world-diverse "seeds" list (gate_seeds convention); fall back
    # to the union of any list-valued entries (old per-world format).
    pool = bank.get("seeds")
    if not isinstance(pool, list):
        pool = sorted({int(s) for v in bank.values() if isinstance(v, (list, tuple))
                       for s in v})
    pool = sorted({int(s) for s in pool})
    seeds = rng.sample(pool, min(a.seeds, len(pool)))
    print(f"panel {len(panel)} tapes; capturing shop trajectories over {len(seeds)} seeds",
          flush=True)
    ckpts = load_checkpoints(a.config)
    print("active checkpoints (day):", [d for d, _ in ckpts], flush=True)
    cell_shops = capture(base, panel, seeds, ckpts)
    panel_paths = panel

    # nested per-cell route: starts at base, gets each checkpoint's branch spliced
    cur = {c: copy.deepcopy(base) for c in cell_shops}
    out = {}
    for (day, split) in ckpts:
        groups = defaultdict(list)
        for c, per in cell_shops.items():
            key = per.get(day)
            if key:
                groups[key].append(c)
        out[str(day)] = {}
        for key, cells in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            if len(cells) < a.min_cells:
                continue
            use = rng.sample(cells, min(a.cells, len(cells)))
            evc = [(panel_paths[oi], s, seat) for (oi, s, seat) in use]
            parent = cur[use[0]]             # same base prefix across this key
            prefix = copy.deepcopy(parent[:split])
            pt = SS.write_tape(parent, os.path.join(WORK, "parent.tape"))
            base_sc = SS.batch_eval_cells([pt], evc, a.threads)[0]["score"]
            best, best_sc = parent, base_sc
            for g in range(a.gens):
                muts = []
                for _ in range(a.lam):
                    m = SS.mutate(best, rng, window=80, field_ops=True)
                    m[:split] = copy.deepcopy(prefix)
                    muts.append(m)
                paths = [SS.write_tape(m, os.path.join(WORK, f"m{i}.tape"))
                         for i, m in enumerate(muts)]
                res = SS.batch_eval_cells(paths, evc, a.threads)
                gi = max(range(len(muts)), key=lambda i: res[i]["score"])
                if res[gi]["score"] > best_sc:
                    best, best_sc = muts[gi], res[gi]["score"]
            tag = "  <== ADAPT" if best_sc > base_sc + 1e-9 else ""
            print(f"  D{day:<2} {key[:34]:<34} base {base_sc:.3f} -> {best_sc:.3f}"
                  f"  ({len(use)} cells){tag}", flush=True)
            if best_sc > base_sc + 1e-9:
                out[str(day)][key] = {"cont": best[split:719], "score": best_sc,
                                      "base": base_sc, "n": len(use)}
                for c in cells:              # nest: carry this branch forward
                    cur[c] = copy.deepcopy(cur[c][:split]) + best[split:719]
    json.dump(out, open(a.out, "w"))
    tot = sum(len(v) for v in out.values())
    print(f"\n{tot} multi-checkpoint adaptive branches -> {a.out}", flush=True)


if __name__ == "__main__":
    main()
