"""Assemble `src/trackp/compiled/main.py` -- the compiled-agent bridge.

The shipped `main.py` is TWO things concatenated:

  1. `bridge.py` -- the subprocess transport, the action validator and the
     watchdog. Pure stdlib, no imports beyond json/os/subprocess/threading.
  2. the pure-Python fallback planner, which is exactly the agent
     `src/trackp/build_econ_agent.py --genome skeleton` emits, with its
     `agent()` renamed `_fallback_agent()`.

Part 2 is the SAME policy the Rust binary implements (rustengine/src/policy.rs
is a line-by-line port of it), so a fallback costs speed, not strategy. That
identity is asserted by tests/test_compiled_agent.py.

    python src/trackp/compiled/build_main.py
"""
from __future__ import annotations
from kaggriculture.paths import ROOT

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACKP = ROOT
SRC = os.path.dirname(TRACKP)
sys.path.insert(0, TRACKP)


def build(out_path: str | None = None) -> str:
    import build_econ_agent as bea  # noqa: E402  (path set above)

    tmp = os.path.join(ROOT, ".local", "candidates", "trackp_compiled",
                       "_fallback_src.py")
    bea.render(bea.skeleton_genome(), tmp)
    with open(tmp, encoding="utf-8") as fh:
        fallback = fh.read()

    # Rename the entry point and strip the module docstring/import: the bridge
    # already owns both. `math` is re-imported harmlessly by the fallback body,
    # so only the entry point actually has to change.
    fallback, n = re.subn(r"^def agent\(obs, cfg=None\):",
                          "def _fallback_agent(obs, cfg=None):",
                          fallback, flags=re.M)
    if n != 1:
        raise SystemExit(f"expected exactly one agent() def, found {n}")

    with open(os.path.join(HERE, "bridge.py"), encoding="utf-8") as fh:
        bridge = fh.read()

    banner = (
        '"""Kaggriculture Track-P COMPILED agent (Phase A transport spike).\n'
        "\n"
        "Generated by src/trackp/compiled/build_main.py -- DO NOT EDIT.\n"
        "Edit src/trackp/compiled/bridge.py (transport) or\n"
        "src/kaggriculture/trackp/build_econ_agent.py (policy) and rebuild.\n"
        "\n"
        "Layout of the submission tarball:\n"
        "    main.py     this file (pure stdlib)\n"
        "    kagg        the compiled Linux x86_64 searcher\n"
        "\n"
        "main.py spawns ./kagg (found relative to __file__) once per episode\n"
        "and speaks one observation JSON per line to it. Every failure --\n"
        "spawn, crash, timeout, malformed reply, illegal action -- degrades to\n"
        "the pure-Python planner below, which is the same policy. agent()\n"
        "never raises.\n"
        '"""\n'
    )

    # The __main__ guard goes LAST: `_selftest()` calls agent(), which may need
    # `_fallback_agent`, and a guard spliced mid-file would run before that
    # def exists.
    tail = (
        '\n\nif __name__ == "__main__":\n'
        '    if "--selftest" in sys.argv:\n'
        "        raise SystemExit(_selftest())\n"
    )
    src = banner + "\n" + bridge + "\n\n" + _strip_docstring(fallback) + tail
    out_path = out_path or os.path.join(HERE, "main.py")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(src)
    return out_path


def _strip_docstring(src: str) -> str:
    """Drop the generated agent's leading module docstring (the bridge banner
    replaces it); everything else is kept verbatim."""
    if not src.startswith('"""'):
        return src
    end = src.find('"""', 3)
    return src[end + 3:].lstrip("\n")


if __name__ == "__main__":
    p = build(sys.argv[1] if len(sys.argv) > 1 else None)
    print(f"wrote {p} ({os.path.getsize(p):,} bytes)")
