"""Kaggriculture Track-P COMPILED agent (Phase A transport spike).

Generated by src/trackp/compiled/build_main.py -- DO NOT EDIT.
Edit src/trackp/compiled/bridge.py (transport) or
src/trackp/build_econ_agent.py (policy) and rebuild.

Layout of the submission tarball:
    main.py     this file (pure stdlib)
    kagg        the compiled Linux x86_64 searcher

main.py spawns ./kagg (found relative to __file__) once per episode
and speaks one observation JSON per line to it. Every failure --
spawn, crash, timeout, malformed reply, illegal action -- degrades to
the pure-Python planner below, which is the same policy. agent()
never raises.
"""

import json
import os
import subprocess
import sys
import threading
import time

# --------------------------------------------------------------- constants --

# ---------------------------------------------------------------- the search --
#
# Per-turn SEARCH budget handed to `kagg play`, in milliseconds. 0 = the plain
# skeleton policy, which is byte-identical to the Python fallback below.
#
# This is a WALL-CLOCK budget: the searcher checks the clock after every
# rollout, so a slower core buys fewer rollouts rather than more milliseconds.
# What a slower core does stretch is the fixed overhead (json.dumps, the pipe,
# the one rollout in flight when the deadline passes), which is why the
# watchdog below is sized as budget + slack and not as a constant.
#
# TRACKP_BUDGET_MS overrides it and is read by the BINARY too, so a measurement
# can sweep budgets against one packed artefact. Kaggle never sets it, so the
# shipped value is the constant.
#
# 0 -- THE SEARCH IS OFF, AND THAT IS A MEASUREMENT, NOT A DEFAULT.
#
# It shipped at 150 until 2026-09-03 22:40. The base-economy fix of that
# evening (docs/history/trackp-base-economy-2026-09-03.md: land as early as cash
# allows + the mined lean hire ramp) raised the skeleton path so far that the
# searcher, whose value function and knob space were fitted around the OLD
# weak skeleton, now hill-climbs AWAY from a better economy.
#
# Re-measured after the rebuild on the official vendored interpreter, the real
# tarball untarred inside Linux, 5 gauntlet opponents x 4 seeds x both seats =
# 40 cells per row, the SAME cells both times:
#
#     budget   W-D-L    own median   own mean   opp median   share   worst turn
#        0    0-0-40      63,857      64,791     135,090     33.0%     29.5 ms
#      150    0-0-40      48,543      50,036     115,840     29.7%    266.7 ms
#
# Paired cell for cell, the searcher is worth **-14,755 of own bank on the
# mean and is richer on only 11 of the 40 cells (two-sided sign test
# p = 0.0064)**, for exactly the same zero wins. It also BREAKS THE LATENCY
# BAR: 266.7 ms worst under the 6-worker load, past the 250 ms line that keeps
# 4x margin on the 1,000 ms actTimeout.
#
# Three further things budget 0 buys, each of which matters more than a search
# that measures negative:
#
#   1. **A blocked fork/exec on Kaggle costs NOTHING.** At budget 0 the
#      compiled path is byte-identical to the inlined Python fallback
#      (tests/test_compiled_agent.py, the identity gate). If the sandbox
#      refuses to spawn the binary, the agent plays the same game, action for
#      action. Nobody has proven Kaggle permits fork/exec; this makes that
#      question free to ask.
#   2. **It is REPRODUCIBLE.** A wall-clock budget makes the agent
#      non-deterministic, and src/determinism.py's rule is that a paired A/B
#      over a non-reproducible agent is INVALID, not merely noisy. Budget 0
#      returns the same bank for the same seed and seat, every time.
#   3. **34x latency margin under load** (29.5 ms worst over 28,760 timed
#      turns with 6 cells in flight; 9.1 ms on a quiet box) instead of ~4x.
#
# Latency by budget on the rebuilt binary, quiet box, 719 turns/cell:
#
#     budget    mean     p95    worst
#        0      1.06     1.3     9.1
#      100     99.2   103.9   105.2
#      150    148.2   155.6   159.8
#
# The overhead above a non-zero budget is a flat 7-10 ms, NOT a multiple of it:
# `budget_ms` is WALL CLOCK, checked after every rollout, so a slower core buys
# fewer rollouts rather than more milliseconds. That is exactly why raising the
# budget cannot rescue the searcher on Kaggle either -- 1.6 vCPU would run a
# WEAKER search than the 150 ms row above, and that row already measures
# negative here.
#
# DO NOT raise this without a fresh paired sign test against budget 0 on the
# gauntlet. The searcher is not deleted -- `--budget-ms N` and
# TRACKP_BUDGET_MS still turn it on for measurement, and search_selftest still
# proves a zero-budget searcher is action-for-action the skeleton.
SEARCH_BUDGET_MS = 0


def _budget_ms():
    try:
        v = int(os.environ.get("TRACKP_BUDGET_MS", "").strip())
    except (TypeError, ValueError):
        return SEARCH_BUDGET_MS
    return v if v >= 0 else SEARCH_BUDGET_MS


# Per-turn watchdog. actTimeout is 1.0 s. The search is told to finish in
# `budget`; 150 ms of slack covers the straggling rollout, the JSON round trip
# and a Kaggle core that is slower at the fixed work. Floor 0.25 s keeps the
# Phase-A (budget 0) behaviour exactly as it was measured; the 0.60 s ceiling
# keeps >= 40% of actTimeout in hand no matter what budget is configured.
#
# The FIRST turn also pays process start-up, hence a separate, larger budget.
TURN_BUDGET = min(0.60, max(0.25, _budget_ms() / 1000.0 + 0.15))

# The FIRST turn also pays process start-up, so it gets its own, larger budget.
#
# **It used to be 1.50 s and that was a BUG, found 2026-09-03 by finally firing
# the timeout path.** `actTimeout` is 1.0 s. A watchdog longer than the engine's
# own limit cannot protect anything: in the one situation it exists for -- the
# binary spawns but never answers -- it would sit on turn 1 for 1.5 s and hand
# the engine a turn it had already timed out, converting a harmless fallback
# into a possible forfeit. Measured directly: breakage case D (a `kagg` that
# reads the request and sleeps) produced a worst turn of **1,503 ms**.
#
# The old value rested on an ASSUMPTION written into the Phase-A doc -- "the
# engine has not started the clock on turn 1 in the same way" -- that was never
# measured. Nothing should rest on that.
#
# 0.50 s is sized from the measurement instead: spawn + the first day plan is
# under 30 ms on Linux with 6 cells in flight (the worst single turn of all
# 28,760 in the budget-0 gauntlet, first turns included), so this is ~16x the
# observed cost, ~8x on a core twice as slow, and still leaves HALF of
# actTimeout in hand.
FIRST_BUDGET = 0.50

# Every op the interpreter recognises. Anything else is a silent no-op on the
# engine side, which is exactly why it must be caught HERE: an illegal action
# looks like laziness, not like a bug.
UNIT_OPS = frozenset((
    "PASS", "NORTH", "SOUTH", "EAST", "WEST", "PLANT", "WATER", "HARVEST",
    "FERTILIZE", "DIG", "BUILD_COOP", "BUILD_PASTURE", "FEED", "CARE",
    "COLLECT_FERTILIZER", "DROP", "PICKUP", "PLACE",
))
MARKET_OPS = frozenset((
    "HIRE", "BUY_LAND", "BUY_SEED", "BUY_PRODUCT", "BUY_ANIMAL", "SELL",
))
MARKET_NEEDS_ARGS = frozenset(("BUY_SEED", "BUY_PRODUCT", "BUY_ANIMAL", "SELL"))
MAX_MARKET_ORDERS = 10

# Diagnostics the harness reads. Never used for a decision.
STATS = {
    "turns": 0,          # agent() calls
    "bridge": 0,         # answered by the compiled binary
    "fallback": 0,       # answered by the pure-Python planner
    "spawn_fail": 0,
    "timeouts": 0,
    "bad_reply": 0,
    "repairs": 0,        # actions the validator had to fix
    "worst_ms": 0.0,
    "reason": "",
    "budget_ms": 0,      # the search budget this episode actually ran at
}

_BIN = {"proc": None, "q": None, "dead": False, "started": False}


# ----------------------------------------------------------------- transport --

def _binary_path():
    """The compiled searcher, found RELATIVE TO THIS FILE.

    A submission tarball is unpacked into /kaggle_simulations/agent/, but the
    path is not contractual and hard-coding it makes the artefact untestable
    anywhere else. __file__ is authoritative in both places; the documented
    Kaggle path is only a fallback probe.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    names = ("kagg", "kagg.exe")
    roots = (here, "/kaggle_simulations/agent")
    for root in roots:
        for name in names:
            p = os.path.join(root, name)
            if os.path.exists(p):
                return p
    return None


def _reader(pipe, q):
    try:
        for line in pipe:
            q.append(line)
    except Exception:
        pass
    finally:
        q.append(None)


def _spawn():
    """Start the searcher once. Any failure marks the bridge dead for good."""
    _BIN["started"] = True
    path = _binary_path()
    if not path:
        _BIN["dead"] = True
        STATS["spawn_fail"] += 1
        STATS["reason"] = "binary not found"
        return
    try:
        if not os.access(path, os.X_OK):
            try:
                os.chmod(path, 0o755)
            except OSError:
                pass
        budget = _budget_ms()
        STATS["budget_ms"] = budget
        proc = subprocess.Popen(
            [path, "play", "--budget-ms", str(budget)],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True, encoding="utf-8", bufsize=1,
            cwd=os.path.dirname(os.path.abspath(path)),
        )
    except Exception as exc:                                  # noqa: BLE001
        _BIN["dead"] = True
        STATS["spawn_fail"] += 1
        STATS["reason"] = "spawn: %s" % (exc,)
        return
    q = []
    t = threading.Thread(target=_reader, args=(proc.stdout, q), daemon=True)
    t.start()
    _BIN["proc"] = proc
    _BIN["q"] = q


def _kill(reason):
    """Retire the bridge permanently.

    A timed-out turn leaves a reply in flight, and without a request/response
    tag there is no way to re-pair the stream afterwards -- a late answer would
    silently become the NEXT turn's action. So one timeout retires the bridge
    for the rest of the episode and every later turn is planned in Python. That
    is a deliberate trade: a correct weaker agent over a fast desynchronised
    one.
    """
    _BIN["dead"] = True
    STATS["reason"] = STATS["reason"] or reason
    proc = _BIN["proc"]
    _BIN["proc"] = None
    _BIN["q"] = None
    if proc is None:
        return
    try:
        proc.kill()
    except Exception:                                         # noqa: BLE001
        pass


def _ask(payload, budget):
    """One request/response round trip, or None."""
    proc = _BIN["proc"]
    q = _BIN["q"]
    if proc is None or q is None:
        return None
    try:
        proc.stdin.write(payload + "\n")
        proc.stdin.flush()
    except Exception:                                         # noqa: BLE001
        _kill("stdin write failed")
        return None
    deadline = time.time() + budget
    while not q:
        if time.time() > deadline:
            STATS["timeouts"] += 1
            _kill("turn exceeded %.2fs" % budget)
            return None
        if proc.poll() is not None:
            _kill("process exited rc=%s" % proc.poll())
            return None
        time.sleep(0.0005)
    line = q.pop(0)
    if line is None:
        _kill("stdout closed")
        return None
    try:
        reply = json.loads(line)
    except Exception:                                         # noqa: BLE001
        STATS["bad_reply"] += 1
        _kill("malformed reply")
        return None
    if not isinstance(reply, dict):
        STATS["bad_reply"] += 1
        _kill("reply is not an object")
        return None
    return reply


# ----------------------------------------------------------------- validator --

def _clean_unit(op):
    """One unit action, repaired to something the interpreter accepts."""
    if not isinstance(op, (list, tuple)) or not op:
        return None
    name = op[0]
    if not isinstance(name, str) or name not in UNIT_OPS:
        return None
    out = [name]
    for tok in op[1:3]:
        if isinstance(tok, bool):
            return None
        if isinstance(tok, (int, float)):
            out.append(str(int(tok)))
        elif isinstance(tok, str):
            out.append(tok)
        else:
            return None
    if name in ("PLANT", "PLACE", "PICKUP") and len(out) < 2:
        return None
    return out


def _clean_order(order):
    if not isinstance(order, (list, tuple)) or not order:
        return None
    name = order[0]
    if not isinstance(name, str) or name not in MARKET_OPS:
        return None
    if name not in MARKET_NEEDS_ARGS:
        return [name]
    if len(order) < 3:
        return None
    item = order[1]
    if not isinstance(item, str) or not item:
        return None
    try:
        n = int(order[2])
    except (TypeError, ValueError):
        return None
    if n <= 0:
        return None
    return [name, item, str(n)]


def _validate(action, n_hands):
    """Make ANY reply legal, or return None if it cannot be salvaged.

    Enforced here, not trusted from the binary: `hands` aligned POSITIONALLY
    with farms[me]["hands"], at most 10 market orders, known op names only.
    """
    if not isinstance(action, dict):
        return None
    repairs = 0

    farmer = _clean_unit(action.get("farmer"))
    if farmer is None:
        farmer = ["PASS"]
        repairs += 1

    raw = action.get("hands")
    hands = []
    if isinstance(raw, (list, tuple)):
        for op in raw[:n_hands]:
            c = _clean_unit(op)
            if c is None:
                c = ["PASS"]
                repairs += 1
            hands.append(c)
    while len(hands) < n_hands:
        hands.append(["PASS"])
        repairs += 1

    market = []
    raw = action.get("market")
    if isinstance(raw, (list, tuple)):
        for order in raw:
            if len(market) >= MAX_MARKET_ORDERS:
                repairs += 1
                break
            c = _clean_order(order)
            if c is None:
                repairs += 1
                continue
            market.append(c)

    STATS["repairs"] += repairs
    return {"farmer": farmer, "hands": hands, "market": market}


# --------------------------------------------------------------------- agent --

def _n_hands(obs):
    try:
        me = int(obs["player"])
        return len(obs["farms"][me]["hands"] or [])
    except Exception:                                         # noqa: BLE001
        return 0


def _plain(o):
    """kaggle-environments hands agents a Struct (a dict subclass). json.dumps
    copes, but a hostile/odd container must not be able to raise here."""
    if isinstance(o, dict):
        return dict((str(k), _plain(v)) for k, v in o.items())
    if isinstance(o, (list, tuple)):
        return [_plain(v) for v in o]
    if isinstance(o, (str, int, float, bool)) or o is None:
        return o
    return str(o)


def _beacon(tag):
    """One line on stderr, which kaggle-environments captures into the
    episode's per-agent `logs`.

    This is the ONLY way to learn from the ladder whether the subprocess
    transport actually worked there. A blocked fork/exec would look exactly
    like a normal game -- the Python fallback covers for it and the agent
    still plays a legal episode -- so without a beacon we would ship a
    compiled agent and never know it ran interpreted. Two lines per episode,
    never on the hot path.
    """
    try:
        sys.stderr.write("TRACKP %s %s\n" % (tag, json.dumps(STATS)))
        sys.stderr.flush()
    except Exception:                                         # noqa: BLE001
        pass


def agent(obs, cfg=None):
    t0 = time.time()
    STATS["turns"] += 1
    action = None
    try:
        if not _BIN["started"]:
            _spawn()
        if not _BIN["dead"]:
            try:
                payload = json.dumps(obs, separators=(",", ":"))
            except Exception:                                 # noqa: BLE001
                payload = json.dumps(_plain(obs), separators=(",", ":"))
            budget = FIRST_BUDGET if STATS["bridge"] == 0 else TURN_BUDGET
            reply = _ask(payload, budget)
            if reply is not None:
                action = _validate(reply, _n_hands(obs))
        if action is not None:
            STATS["bridge"] += 1
        else:
            STATS["fallback"] += 1
            action = _validate(_fallback_agent(obs, cfg), _n_hands(obs))
    except Exception as exc:                                  # noqa: BLE001
        # Belt and braces. agent() raising costs the whole submission: the
        # upload Validation Episode marks it Error and the slot is spent.
        STATS["reason"] = STATS["reason"] or ("agent: %s" % (exc,))
        action = None
    if action is None:
        action = {"farmer": ["PASS"], "hands": [["PASS"]] * _n_hands(obs),
                  "market": []}
    dt = (time.time() - t0) * 1000.0
    if dt > STATS["worst_ms"]:
        STATS["worst_ms"] = dt
    if STATS["turns"] == 1:
        _beacon("start")
    elif int(_get_step(obs)) >= 717:
        _beacon("end")
    return action


def _get_step(obs):
    try:
        return obs["step"]
    except Exception:                                         # noqa: BLE001
        return 0


def _selftest():
    """`python main.py --selftest` -- prove the binary answers, without an
    engine. Prints the day-0 hour-0 action and the transport verdict."""
    obs = json.loads(sys.stdin.read())
    a = agent(obs)
    print(json.dumps(a))
    print(json.dumps(STATS), file=sys.stderr)
    return 0 if STATS["fallback"] == 0 else 1


import math                                                      # noqa: F401

GENOME = {'land': {'NE': 0, 'SW': 5, 'SE': -1}, 'hires': [5, 4, 4, 5, 4, 5, 8, 8, 10, 11, 11, 11, 9, 10, 10, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11], 'herd': {'COW': [[0, 1], [2, 2], [3, 3], [4, 4], [5, 5], [7, 6], [10, 7], [13, 8], [16, 9]], 'SHEEP': [[0, 1], [6, 2], [9, 3], [12, 4], [15, 5]], 'GOOSE': []}, 'tiles': {'MELON': 12, 'STRAWBERRY': 38, 'CARROT': 0}, 'window': {'MELON': [4, 12], 'STRAWBERRY': [5, 14], 'CARROT': [0, 24], 'WHEAT': [0, 25]}, 'floor_seed': 20, 'floor_straw': 700, 'floor_land': 500, 'land_reserve_lead': 0, 'floor_animal': 300, 'hire_slack': -1, 'pen_lookahead': 5, 'feed_buffer': 6, 'fert_crop': 'STRAWBERRY', 'fert_buy': 0, 'care': True, 'sell_cap': {'MELON': 24, 'WOOL': 40, 'STRAWBERRY': 60, 'MILK': 40, 'EGG': 60, 'CARROT': 60, 'TOMATO': 60, 'FERTILIZER': 60}, 'fert_keep': 12, 'sell_floor': 0.0, 'plant_pace': 0.95, 'valve_hi': 55, 'valve_lo': 45, 'sell_order': 0, 'sell_prio': ['MELON', 'FERTILIZER', 'STRAWBERRY', 'MILK', 'WOOL', 'CARROT', 'TOMATO', 'EGG', 'WHEAT'], 'hour0_sells': 0, 'drop_daily': 0, 'hold_price': {}, 'demand_crops': {}, 'herd_gate': {}}

TPD = 24
BOARD = 10
LAST_DAY = 29
MAX_HIRE = 10               # the hour-0 market batch holds 10 orders
SHED = ((4, 4), (5, 4), (4, 5), (5, 5))
LAND_ORDER = ("NE", "SW", "SE")
LAND_COST = (1000, 2000, 4000)
BASE_PRICE = {"WHEAT": 25, "CARROT": 35, "TOMATO": 60, "STRAWBERRY": 120,
              "MELON": 250, "EGG": 50, "MILK": 160, "WOOL": 200,
              "FERTILIZER": 100}
SELLABLE = ("MELON", "STRAWBERRY", "WOOL", "MILK", "EGG", "CARROT",
            "TOMATO", "FERTILIZER", "WHEAT")
CROPS = {
    "WHEAT":      {"seed": 10, "first": 2, "maxd": 4, "iv": 0, "maxy": 6,
                   "ong": 0},
    "CARROT":     {"seed": 20, "first": 2, "maxd": 3, "iv": 0, "maxy": 4,
                   "ong": 0},
    "TOMATO":     {"seed": 50, "first": 8, "maxd": 8, "iv": 1, "maxy": 4,
                   "ong": 1},
    "STRAWBERRY": {"seed": 100, "first": 10, "maxd": 10, "iv": 2,
                   "maxy": 4, "ong": 1},
    "MELON":      {"seed": 80, "first": 10, "maxd": 12, "iv": 0, "maxy": 6,
                   "ong": 0},
}
ANIMALS = {
    "GOOSE": {"cost": 300, "build": "BUILD_COOP", "pen": "COOP"},
    "COW":   {"cost": 400, "build": "BUILD_PASTURE", "pen": "PASTURE"},
    "SHEEP": {"cost": 500, "build": "BUILD_PASTURE", "pen": "PASTURE"},
}
ANIMAL_PRODUCT = {"GOOSE": "EGG", "COW": "MILK", "SHEEP": "WOOL"}
PLANT_ORDER = ("MELON", "STRAWBERRY", "CARROT", "TOMATO")
# What each shop instance consumes. The town centre eats 1 of every product
# except FERTILIZER every 24 steps; each unlocked shop instance eats 1 of
# each listed product every 4 steps (x2 for a single-product shop). Both are
# ENGINE CONSTANTS, and `town.unlocked_shops` is in the live observation, so
# the day's real demand rate per product is computable at dawn.
SHOP_ITEMS = {
    "BAKERY": ("EGG", "WHEAT"),
    "PIZZA_SHOP": ("MILK", "TOMATO", "WHEAT"),
    "BRUNCH_SPOT": ("EGG", "WHEAT", "STRAWBERRY"),
    "YARN_STORE": ("WOOL",),
    "ICE_CREAM_SHOP": ("STRAWBERRY", "MILK", "WHEAT"),
    "PET_CAFE": ("CARROT",),
    "SMOOTHIE_SHOP": ("STRAWBERRY", "MILK"),
    "FARMERS_MARKET": ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY"),
}


def _demand(town):
    """Units/day the town will consume of each product, from the live
    unlocked-shop list. Exact, not estimated."""
    rate = {}
    for s in (_get(town, "unlocked_shops", []) or []):
        lst = SHOP_ITEMS.get(s)
        if not lst:
            continue
        m = 12 if len(lst) == 1 else 6
        for it in lst:
            rate[it] = rate.get(it, 0) + m
    for it in BASE_PRICE:
        if it != "FERTILIZER":
            rate[it] = rate.get(it, 0) + 1
    return rate


def _get(o, k, d=None):
    try:
        v = o[k]
        return d if v is None else v
    except (KeyError, TypeError, IndexError):
        return getattr(o, k, d)


def _quad(t):
    return ("NE" if t[0] >= 5 else "NW") if t[1] < 5 else \
           ("SE" if t[0] >= 5 else "SW")


def _shed_dist(t):
    return min(abs(t[0] - s[0]) + abs(t[1] - s[1]) for s in SHED)


def _tile_order():
    """Boustrophedon per quadrant, each starting at its shed corner: a
    contiguous slice of this order is a cheap walking tour."""
    out = []
    for xs, ys in (((4, 3, 2, 1, 0), (4, 3, 2, 1, 0)),
                   ((5, 6, 7, 8, 9), (4, 3, 2, 1, 0)),
                   ((4, 3, 2, 1, 0), (5, 6, 7, 8, 9)),
                   ((5, 6, 7, 8, 9), (5, 6, 7, 8, 9))):
        for i, y in enumerate(ys):
            row = list(xs) if i % 2 == 0 else list(reversed(xs))
            for x in row:
                if (x, y) not in SHED:
                    out.append((x, y))
    return out


TILE_ORDER = _tile_order()
TIDX = dict((t, i) for i, t in enumerate(TILE_ORDER))
_D = {"day": -1, "plan": None}


def _sched(pairs, d):
    """Cumulative day-indexed cap: the last [day, n] whose day <= d."""
    n = 0
    for pair in (pairs or []):
        try:
            if d >= int(pair[0]):
                n = int(pair[1])
        except (TypeError, ValueError, IndexError):
            continue
    return n


class _U:
    __slots__ = ("pos", "ops", "cap", "start", "loaded")

    def __init__(self, pos, start, cap):
        self.pos = tuple(pos)
        self.ops = []
        self.start = start
        self.cap = cap
        self.loaded = False

    def budget(self):
        return self.cap - len(self.ops)

    def walk(self, t):
        ax, ay = self.pos
        bx, by = t
        while ax < bx and self.budget() > 0:
            self.ops.append(["EAST"])
            ax += 1
        while ax > bx and self.budget() > 0:
            self.ops.append(["WEST"])
            ax -= 1
        while ay < by and self.budget() > 0:
            self.ops.append(["SOUTH"])
            ay += 1
        while ay > by and self.budget() > 0:
            self.ops.append(["NORTH"])
            ay -= 1
        self.pos = (ax, ay)

    def act(self, op):
        if self.budget() <= 0:
            return False
        self.ops.append(op)
        if op[0] in ("HARVEST", "COLLECT_FERTILIZER"):
            self.loaded = True
        return True


def _cost(pos, tile, ops):
    return abs(pos[0] - tile[0]) + abs(pos[1] - tile[1]) + len(ops)


ANIMAL_RATE = {"COW": 3.0, "SHEEP": 2.0, "GOOSE": 4.0}  # ~product units/day
DUMP_PROOF = ("EGG", "WHEAT")                              # log-priced, never glut


def _plan(d, farm, priv, mkt, town, opp=None):
    g = GENOME
    money = float(_get(farm, "money", 0) or 0)
    tiles = _get(farm, "tiles", []) or []
    shed = {}
    for k, v in (_get(priv, "shed", {}) or {}).items():
        shed[k] = int(v or 0)
    seeds = {}
    for k, v in (_get(priv, "seeds", {}) or {}).items():
        seeds[k] = int(v or 0)
    owned = set(_get(farm, "unlocked_quadrants", ["NW"]) or ["NW"])
    prices = dict(_get(mkt, "prices", {}) or {})
    sell_all = d >= LAST_DAY - 1
    final = d >= LAST_DAY

    def tl_at(t):
        try:
            return tiles[t[1]][t[0]]
        except (IndexError, TypeError):
            return "LOCKED"

    # ---- census the REAL board -----------------------------------------
    animals, pens, plants, weeds, empties = [], [], [], [], []
    n_an = {}
    n_cr = {}
    for t in TILE_ORDER:
        if _quad(t) not in owned:
            continue
        tl = tl_at(t)
        if tl == "LOCKED":
            continue
        if tl is None:
            empties.append(t)
            continue
        if not isinstance(tl, dict):
            continue
        if "animal" in tl:
            animals.append((t, tl))
            n_an[tl["animal"]] = n_an.get(tl["animal"], 0) + 1
        elif tl.get("kind") == "PLANT":
            plants.append((t, tl))
            c = tl.get("crop", "WHEAT")
            n_cr[c] = n_cr.get(c, 0) + 1
        elif tl.get("kind") == "WEED":
            weeds.append(t)
        elif tl.get("kind") in ("PASTURE", "COOP"):
            pens.append(t)

    # animals bought on an earlier day are sitting in the shed: THEY are
    # today's placements. Animals bought today land in the shed after the
    # unit turn, so they are placed (and fed, and cared for) tomorrow.
    pen_need = {}
    for sp in ("COW", "SHEEP", "GOOSE"):
        pen_need[sp] = int(shed.get(sp, 0))

    late = []            # (rank, op): everything after the hires

    # ---- hires: the whole crew in the hour-0 batch ----------------------
    hires = g.get("hires") or []
    n_plan = int(hires[min(d, len(hires) - 1)]) if hires else 0
    # THE HOUR-0 SLOT. `farm["hands"]` is cleared every night, so the crew is
    # re-hired from scratch each dawn; from day 8 the ramp asks for ten hands
    # and ten HIRE orders fill all ten of hour 0's market slots -- so for two
    # thirds of the season this seat cannot sell on the first turn of a day.
    # `_process_market` walks slot 0 of BOTH seats, reprices, then slot 1,
    # and `_town_consume` only restocks on steps divisible by 4, so a seat
    # selling at hour 1 always sells into the inventory the hour-0 seller
    # just raised. v43.0_bandit puts 84% of its sells in slot 0.
    # `hour0_sells` buys back the earliest slots by hiring that many fewer
    # hands; the marginal hand is also the most expensive (fib(9) = 55/day).
    n0 = max(0, min(MAX_HIRE, int(g.get("hour0_sells", 0) or 0)))
    n_plan = max(0, min(MAX_HIRE - n0, n_plan))
    fib = [1, 1]
    while len(fib) < max(2, n_plan):
        fib.append(fib[-1] + fib[-2])
    n_h = 0
    spend = 0.0
    for i in range(n_plan):
        c = fib[min(i, len(fib) - 1)]
        if money - spend - c < 40:
            break
        spend += c
        n_h += 1
    money -= spend

    # ---- land: 2 buys, on the schedule, cash-gated ----------------------
    # land_res is the cost of the NEXT scheduled quadrant, withheld from the
    # herd until it is bought. Tiles, not animals, are the binding constraint
    # early: NW holds 24 usable tiles and the skeleton wants 243 plants.
    land_res = 0.0
    n_extra = len(owned) - 1
    if n_extra < 3 and not sell_all:
        nq = LAND_ORDER[n_extra]
        ld = (g.get("land") or {}).get(nq, -1)
        need_land = LAND_COST[n_extra] + float(g.get("floor_land", 300))
        if isinstance(ld, int) and ld >= 0 and d >= ld and money >= need_land:
            late.append((1, ["BUY_LAND"]))
            money -= LAND_COST[n_extra]
        elif isinstance(ld, int) and ld >= 0 and \
                d >= ld - int(g.get("land_reserve_lead", 6)):
            land_res = need_land

    herd = g.get("herd") or {}

    # ---- what a newly available tile should become ----------------------
    want = dict(n_cr)
    tile_t = dict(g.get("tiles") or {})
    windows = g.get("window") or {}
    purse = [money]

    # ---- DEMAND CAPTURE -------------------------------------------------
    # CARROT and TOMATO are the two products nobody supplies: the town eats
    # them every day and neither elite routes nor this planner ever plant
    # them, so their inventory runs a season-long deficit and the price runs
    # away (both are HINGE-priced below I0). The tile target is sized from
    # the REAL consumption rate the unlocked-shop list implies, so a seed
    # that never draws PET_CAFE never grows a carrot.
    dem = g.get("demand_crops") or {}
    if dem:
        rate = _demand(town)
        for c in sorted(dem):
            spec = dem[c] or {}
            mx = int(spec.get("max", 0) or 0)
            if mx <= 0:
                continue
            r = float(rate.get(c, 0))
            if r < float(spec.get("min_rate", 0) or 0):
                continue
            p = float(prices.get(c, BASE_PRICE.get(c, 1)))
            if p < float(spec.get("min_price", 0) or 0) * BASE_PRICE.get(c, 1):
                continue
            per = float(spec.get("per_tile", 0.75) or 0.75)
            tile_t[c] = max(int(tile_t.get(c, 0)),
                            min(mx, int(r / per)))

    def _open(c):
        w = windows.get(c) or [0, 25]
        return int(w[0]) <= d <= int(w[1])

    def _pick():
        """Species for one newly available tile; None to leave it fallow."""
        for c in PLANT_ORDER:
            tgt = int(tile_t.get(c, 0))
            if tgt <= 0 or not _open(c) or want.get(c, 0) >= tgt:
                continue
            if d + CROPS[c]["first"] > LAST_DAY:
                continue
            floor = float(g.get("floor_straw", 250)) \
                if CROPS[c]["seed"] >= 80 else float(g.get("floor_seed", 40))
            if purse[0] < CROPS[c]["seed"] + floor:
                continue
            purse[0] -= CROPS[c]["seed"]
            want[c] = want.get(c, 0) + 1
            return c
        if _open("WHEAT") and d + CROPS["WHEAT"]["first"] <= LAST_DAY and \
                purse[0] >= CROPS["WHEAT"]["seed"] + float(
                    g.get("floor_seed", 40)):
            purse[0] -= CROPS["WHEAT"]["seed"]
            want["WHEAT"] = want.get("WHEAT", 0) + 1
            return "WHEAT"
        return None

    # ---- tasks from what STANDS on the board ----------------------------
    # (tile, ops, priority, needs) -- needs are shed withdrawals
    tasks = []
    fert_left = shed.get("FERTILIZER", 0)
    fert_crop = g.get("fert_crop", "STRAWBERRY")
    for t, tl in animals:
        ops = []
        need = {}
        if not tl.get("fed_today") and not final:
            ops.append(["FEED"])
            need["WHEAT"] = 1
        if int(_get(tl, "yield_units", 0) or 0) > 0:
            ops.append(["HARVEST"])
        if tl.get("fertilizer_available"):
            ops.append(["COLLECT_FERTILIZER"])
        if g.get("care") and not tl.get("cared_today") and not final:
            ops.append(["CARE"])
        if ops:
            tasks.append((t, ops, 0, need))
    for t, tl in plants:
        crop = tl.get("crop", "WHEAT")
        c = CROPS.get(crop) or CROPS["WHEAT"]
        age = d - int(tl.get("planted_day", d) or 0)
        yld = int(_get(tl, "yield_units", 0) or 0)
        ops = []
        need = {}
        if c["ong"]:
            last = c["first"] + c["iv"] * (c["maxy"] - 1)
            if yld > 0 and age >= c["first"]:
                ops.append(["HARVEST"])
            if age < last and not final:
                if crop == fert_crop and fert_left > 0 and \
                        int(tl.get("fertilized_until_day", -1)) < d and \
                        age >= c["first"] - 1 and \
                        (age - (c["first"] - 1)) % max(1, 2 * c["iv"]) == 0:
                    ops.append(["FERTILIZE"])
                    need["FERTILIZER"] = 1
                    fert_left -= 1
                if not tl.get("watered_today"):
                    ops.append(["WATER"])
            elif age >= last and not ops and not sell_all:
                ops.append(["DIG"])
                nxt = _pick()
                if nxt:
                    ops.append(["PLANT", nxt])
                    ops.append(["WATER"])
                    need["SEED_" + nxt] = 1
        else:
            ripe = age >= c["maxd"] or (yld >= c["maxy"] and age >= c["first"])
            if final or sell_all:
                if yld > 0 and age >= c["first"]:
                    ops.append(["HARVEST"])
                elif not final and not tl.get("watered_today"):
                    ops.append(["WATER"])
            elif ripe and yld > 0:
                ops.append(["HARVEST"])
                nxt = _pick()
                if nxt:
                    ops.append(["PLANT", nxt])
                    ops.append(["WATER"])
                    need["SEED_" + nxt] = 1
            elif ripe:
                ops.append(["DIG"])
            elif not tl.get("watered_today"):
                ops.append(["WATER"])
        if ops:
            tasks.append((t, ops, 1, need))
    if not sell_all:
        for t in weeds:
            tasks.append((t, [["DIG"]], 3, {}))
        for t in pens:
            tlp = tl_at(t)
            kind = tlp.get("kind") if isinstance(tlp, dict) else None
            for s in ("COW", "SHEEP", "GOOSE"):
                if ANIMALS[s]["pen"] == kind and pen_need.get(s, 0) > 0:
                    pen_need[s] -= 1
                    ops = [["PLACE", s], ["FEED"]]
                    if g.get("care"):
                        ops.append(["CARE"])
                    tasks.append((t, ops, 2, {"AN_" + s: 1, "WHEAT": 1}))
                    break
        # Tiles the herd will need SOON are held back from the plough: a
        # day-0 board planted wall to wall left every bought animal
        # rotting in the shed until a crop cycle freed a tile.
        look = int(g.get("pen_lookahead", 5))
        soon = 0
        for s in ("COW", "SHEEP", "GOOSE"):
            soon += _sched(herd.get(s), d + look)
        held = max(0, soon - (len(animals) + len(pens)
                              + sum(pen_need.values())))
        free = sorted(empties, key=lambda t: (_shed_dist(t), TIDX.get(t, 0)))
        for t in free:
            placed = False
            for s in ("COW", "SHEEP", "GOOSE"):
                if pen_need.get(s, 0) > 0:
                    pen_need[s] -= 1
                    ops = [[ANIMALS[s]["build"]], ["PLACE", s], ["FEED"]]
                    if g.get("care"):
                        ops.append(["CARE"])
                    tasks.append((t, ops, 2, {"AN_" + s: 1, "WHEAT": 1}))
                    placed = True
                    break
            if placed:
                continue
            if held > 0:
                held -= 1
                continue
            nxt = _pick()
            if nxt:
                tasks.append((t, [["PLANT", nxt], ["WATER"]], 3,
                              {"SEED_" + nxt: 1}))

    # ---- herd ramp, from what the CROPS left behind ---------------------
    # Capital priority is crops > animals > feed: the day-ledger showed
    # dawn money pinned at $41 through day 11 when the herd was funded
    # first, and a farm with no seed money never recovers.
    money = purse[0]
    bought = {}
    # HERD GATE. An animal is only worth its $400-500 if the town will eat
    # what it makes. WOOL's above-I0 price branch is quadratic and floors at
    # I0+59, and the town eats 12 wool/day per YARN_STORE against 1/day from
    # the town centre -- so in a draw with no YARN_STORE our own 5-sheep herd
    # already pins the price at $1 and the marginal wool unit is worth MINUS
    # $80. Both inputs are in the live observation.
    gate = g.get("herd_gate") or {}
    rate_g = _demand(town) if gate else {}
    # OPPONENT-ADAPTIVE HERD MIX (2026-09-08). Keep the total herd-size schedule
    # (how many animals the cash/labour supports by day) but ALLOCATE the mix to
    # the animal whose product the town wants and the OPPONENT is NOT already
    # flooding. Producing into an uncrowded product is the whole contested
    # ceiling: a mirror-herd floods the shared market and halves the price,
    # while the same herd pointed at a product the opponent skipped keeps the
    # price up. demand is exact (shops); opponent supply is read from its board.
    # Adapt only from day 6 (shops + the opponent's early herd are revealed;
    # before that there is no signal and the tuned skeleton is best). Between
    # checkpoints the derived mix is stable because the signal is.
    if g.get("adaptive_herd", 0) and d >= 6 and not sell_all:
        demand = _demand(town)
        opp_an = {}
        for _row in (_get(opp or {}, "tiles", []) or []):
            for _t in (_row or []):
                if isinstance(_t, dict) and _t.get("animal"):
                    opp_an[_t["animal"]] = opp_an.get(_t["animal"], 0) + 1

        _planbuy = {}

        def _an_score(sp):
            # Realized $/animal: a herd of rate units/day sells the part the
            # town still wants (headroom) near base price, the oversupplied
            # rest at the floor -- $1 for glut products, ~half-base for the
            # log-priced dump-proof ones (EGG). This picks sheep in YARN
            # worlds, geese in PET_CAFE worlds, and stops at saturation.
            pr = ANIMAL_PRODUCT[sp]
            base_p = float(BASE_PRICE.get(pr, 1))
            rate = ANIMAL_RATE[sp]
            combined = (opp_an.get(sp, 0) + n_an.get(sp, 0) + shed.get(sp, 0)
                        + _planbuy.get(sp, 0)) * rate
            head = max(0.0, float(demand.get(pr, 1)) - combined)
            at_base = min(rate, head)
            floor_p = 0.5 * base_p if pr in DUMP_PROOF else 1.0
            return at_base * base_p + (rate - at_base) * floor_p

        total_cap = sum(_sched(herd.get(sp), d) for sp in ANIMALS)
        # herd gate: a floored product's animal is dropped from the menu
        allowed = set(ANIMALS)
        for sp in ANIMALS:
            spec = gate.get(sp)
            if spec:
                pr = ANIMAL_PRODUCT[sp]
                base_p = float(BASE_PRICE.get(pr, 1))
                px = float(prices.get(pr, base_p))
                if float(rate_g.get(pr, 0)) < float(spec.get("min_rate", 0)) \
                        or px < float(spec.get("min_price", 0)) * base_p:
                    allowed.discard(sp)
        have_total = sum(n_an.get(sp, 0) + shed.get(sp, 0) for sp in ANIMALS)
        floor = float(g.get("floor_animal", 250)) + land_res
        guard = 0
        while have_total < total_cap and guard < 40:
            guard += 1
            cand = [sp for sp in allowed
                    if money >= ANIMALS[sp]["cost"] + floor
                    and _an_score(sp) > 0]
            if not cand:
                break
            sp = max(cand, key=_an_score)
            late.append((2, ["BUY_ANIMAL", sp, 1]))
            money -= ANIMALS[sp]["cost"]
            bought[sp] = bought.get(sp, 0) + 1
            _planbuy[sp] = _planbuy.get(sp, 0) + 1   # balances the mix
            have_total += 1
    elif not sell_all:
        for sp in ("COW", "SHEEP", "GOOSE"):
            cap = _sched(herd.get(sp), d)
            spec = gate.get(sp)
            if spec:
                pr = ANIMAL_PRODUCT[sp]
                base_p = float(BASE_PRICE.get(pr, 1))
                px = float(prices.get(pr, base_p))
                if float(rate_g.get(pr, 0)) < float(spec.get("min_rate", 0)) \
                        or px < float(spec.get("min_price", 0)) * base_p:
                    cap = min(cap, int(spec.get("floor", 0)))
            have = n_an.get(sp, 0) + shed.get(sp, 0)
            cost = ANIMALS[sp]["cost"]
            floor = float(g.get("floor_animal", 250)) + land_res
            while have < cap and money >= cost + floor:
                late.append((2, ["BUY_ANIMAL", sp, 1]))
                money -= cost
                bought[sp] = bought.get(sp, 0) + 1
                have += 1
    fbuy = int(g.get("fert_buy", 0) or 0)
    if fbuy > 0 and 6 <= d <= 24 and money > 2000:
        n = min(fbuy, int((money - 1500) // 110))
        if n > 0:
            late.append((3, ["BUY_PRODUCT", "FERTILIZER", n]))
            money -= n * 110

    # ---- tomorrow's feed, bought today so the dawn pickup can find it ---
    n_beasts = len(animals)
    beasts_tomorrow = n_beasts + sum(shed.get(s, 0) for s in ANIMALS) \
        + sum(bought.values())
    reserve_w = 0
    if beasts_tomorrow and not final:
        reserve_w = beasts_tomorrow + int(g.get("feed_buffer", 6))

    # ---- pace: expansion never starves the standing farm ----------------
    # Priced against the PLANNED crew, so the pace decision does not depend on
    # the hire trim below (which is decided from the paced task list).
    cap_ops = (1 + n_h) * (TPD - 1)
    tend = sum(len(o) + 2 for _t, o, p, _n in tasks if p <= 2)
    room = max(0, int(cap_ops * float(g.get("plant_pace", 0.95))) - tend)
    keep, grow = [], []
    for tk in tasks:
        if tk[2] >= 3 and any(k.startswith("SEED_") for k in tk[3]):
            grow.append(tk)
        else:
            keep.append(tk)
    used = 0
    for tk in grow:
        c = len(tk[1]) + 2
        if used + c > room:
            continue
        used += c
        keep.append(tk)
    tasks = keep
    tasks.sort(key=lambda tk: (TIDX.get(tk[0], 0),))

    # ---- hire to the WORK, not to a fixed ramp --------------------------
    # An idle hand still costs its fibonacci fee. Measured on the skeleton:
    # 2,387 PASS unit-turns a season against the top-30 field's 515, most of
    # them on days 1-9 when the farm is one quadrant and ten hands are hired.
    # `hire_slack` = -1 keeps the old behaviour (hire the ramp blindly);
    # >= 0 hires only the hands the paced task list can actually feed, plus
    # that many spares. The fee for the dropped hands is simply never spent,
    # so it shows up as higher money at tomorrow's dawn.
    slack = int(g.get("hire_slack", -1))
    if slack >= 0 and n_h > 0:
        need = sum(len(o) + 2 for _t, o, _p, _n in tasks)
        n_h = min(n_h, max(0, -(-need // (TPD - 1)) - 1) + slack)

    # ---- the crew (every hand hired at hour 0 -> deterministic spawn) ---
    units = [_U(SHED[0], 1, TPD - 1)]
    for k in range(n_h):
        units.append(_U(SHED[(k + 1) % 4], 1, TPD - 1))

    # ---- assign: contiguous tours, shed withdrawals batched up front ----
    shed_pool, field_pool = [], []
    for tk in tasks:
        if any(not k.startswith("SEED_") for k in tk[3]):
            shed_pool.append(tk)
        else:
            field_pool.append(tk)
    picked = {}

    # QUADRANT-MATCHED ASSIGNMENT. Units spawn at the four shed corners (one
    # per quadrant); TILE_ORDER is a per-quadrant boustrophedon from that
    # corner. Giving each unit ONLY its own quadrant's tasks turns every tour
    # into a tight local sweep from the spawn corner, instead of a hand walking
    # across the board to a chunk that happened to fall at its pool position.
    def _q(t):
        return (0 if t[1] < 5 else 2) + (1 if t[0] >= 5 else 0)
    uq = {0: [], 1: [], 2: [], 3: []}
    for u in units:
        uq[_q(u.pos)].append(u)

    def _take(pool, ul, pickup):
        ui = 0
        while pool and ui < len(ul):
            u = ul[ui]
            ui += 1
            if u.budget() <= 0:
                continue
            chunk = []
            items = set()
            pos = u.pos
            budget = u.budget()
            while pool:
                tile, ops, _p, nd = pool[0]
                new_items = items
                if pickup:
                    new_items = items | set(
                        k for k in nd if not k.startswith("SEED_"))
                c = _cost(pos, tile, ops) + (len(new_items) - len(items)
                                             if pickup else 0)
                if budget - c < 0:
                    break
                chunk.append(pool.pop(0))
                items = new_items
                budget -= c
                pos = tile
            if not chunk:
                continue
            if pickup and items:
                tot = {}
                for _t2, _o2, _p2, nd2 in chunk:
                    for k2, v2 in nd2.items():
                        if k2.startswith("SEED_"):
                            continue
                        it = k2[3:] if k2.startswith("AN_") else k2
                        tot[it] = tot.get(it, 0) + v2
                for it in sorted(tot):
                    avail = shed.get(it, 0) - picked.get(it, 0)
                    n = min(tot[it], max(0, avail))
                    if n > 0:
                        u.act(["PICKUP", it, n])
                        picked[it] = picked.get(it, 0) + n
            for tile, ops, _p, _nd in chunk:
                u.walk(tile)
                for o in ops:
                    u.act(o)
        return pool                      # tasks this quadrant could not fit

    for q in (0, 1, 2, 3):
        _take([tk for tk in shed_pool if _q(tk[0]) == q], uq[q], True)
    field_left = []
    for q in (0, 1, 2, 3):
        field_left += _take([tk for tk in field_pool if _q(tk[0]) == q],
                            uq[q], False)
    # global sweep: any unit with spare budget takes the nearest leftover
    for u in units:
        while field_left and u.budget() > 0:
            field_left.sort(key=lambda tk: _cost(u.pos, tk[0], tk[1]))
            tile, ops, _p, _nd = field_left[0]
            if u.budget() < _cost(u.pos, tile, ops):
                break
            field_left.pop(0)
            u.walk(tile)
            for o in ops:
                u.act(o)
    # SAME-DAY MARKETING. Harvested goods sit in the farmer's inventory
    # until `_drop_inventories_to_shed` runs at dusk, so this seat can only
    # ever sell yesterday's harvest -- and `_fresh_sells` reads the shed, so
    # the whole farm is one day late to market every day. v43.0_bandit is
    # not: its melons reached the market DURING day 10 (inventory +49 at the
    # last step of day 10), which is how it took the top of the melon curve
    # ($242/unit against our $169) on a pool that has no shop demand at all
    # and therefore never refills.
    if int(g.get("drop_daily", 0) or 0) and not sell_all:
        for u in units:
            if u.loaded:
                tgt = min(SHED, key=lambda s: abs(u.pos[0] - s[0])
                          + abs(u.pos[1] - s[1]))
                if u.budget() > abs(u.pos[0] - tgt[0]) + abs(u.pos[1] - tgt[1]):
                    u.walk(tgt)
                    u.act(["DROP"])
                    u.loaded = False
    if sell_all:                         # bank the day's take before dusk
        for u in units:
            if u.loaded and u.budget() > 1:
                tgt = min(SHED, key=lambda s: abs(u.pos[0] - s[0])
                          + abs(u.pos[1] - s[1]))
                u.walk(tgt)
                u.act(["DROP"])

    # ---- seed: exactly the plantings labour actually scheduled ----------
    planted = {}
    for u in units:
        for o in u.ops:
            if o[0] == "PLANT":
                planted[o[1]] = planted.get(o[1], 0) + 1
    seed_orders = []
    for sp in sorted(planted):
        n = planted[sp] - seeds.get(sp, 0)
        if n > 0:
            seed_orders.append(["BUY_SEED", sp, n])

    # ---- feed wheat for TOMORROW ----------------------------------------
    short = reserve_w - (shed.get("WHEAT", 0) - picked.get("WHEAT", 0))
    if short > 0:
        late.append((4, ["BUY_PRODUCT", "WHEAT", short]))

    # ---- sells: on production, above the reserves -----------------------
    caps = dict(g.get("sell_cap") or {})
    floor = float(g.get("sell_floor", 0.0) or 0.0)
    sold = {}
    for item in SELLABLE:
        have = shed.get(item, 0) - picked.get(item, 0)
        if item == "WHEAT" and not sell_all:
            have -= reserve_w
        elif item == "FERTILIZER" and not sell_all:
            have -= int(g.get("fert_keep", 12))
        if have <= 0:
            continue
        if sell_all:
            sold[item] = have
            continue
        p = float(prices.get(item, BASE_PRICE.get(item, 25)))
        if floor > 0 and p < floor * BASE_PRICE.get(item, 25):
            continue
        q = min(have, int(caps.get(item, 999)))
        if q > 0:
            sold[item] = q
    # pressure valve: the shed caps at 100 TOTAL, dusk overflow is DROPPED
    total = sum(shed.values()) - sum(picked.values()) - sum(sold.values())
    v_hi = int(g.get("valve_hi", 55))
    v_lo = int(g.get("valve_lo", 45))
    if not sell_all and total > v_hi:
        for item in ("WHEAT", "EGG", "FERTILIZER", "CARROT", "TOMATO",
                     "MILK", "STRAWBERRY", "WOOL", "MELON"):
            room2 = shed.get(item, 0) - picked.get(item, 0) - sold.get(item, 0)
            if item == "WHEAT":
                room2 -= reserve_w
            take = min(room2, total - v_lo)
            if take > 0:
                sold[item] = sold.get(item, 0) + take
                total -= take
            if total <= v_lo:
                break

    # ---- serialise the market queue (hires FIRST: hour-0 batch) ---------
    sell_q = _order_sells([["SELL", item, int(sold[item])]
                           for item in sorted(sold) if sold[item] > 0], prices)
    # The reserved sells go at slot 0, AHEAD of the hires and of the day's
    # purchases, on purpose: slot index is the price ladder, and a SELL that
    # commits in an earlier slot also credits money the later HIRE/BUY slots
    # can spend -- the dawn purse is $132-$2,600 through day 13.
    queue = list(sell_q[:n0])
    queue.extend([["HIRE"]] * n_h)
    queue.extend(seed_orders)
    for _r, op in sorted(late, key=lambda x: x[0]):
        queue.append(op)
    queue.extend(sell_q[n0:])

    plan = []
    for h in range(TPD):
        mk = queue[h * 10:(h + 1) * 10]
        row = {"farmer": ["PASS"], "hands": [], "market": mk}
        u0 = units[0]
        if h >= u0.start and h - u0.start < len(u0.ops):
            row["farmer"] = u0.ops[h - u0.start]
        hands = []
        for u in units[1:]:
            if h >= u.start and h - u.start < len(u.ops):
                hands.append(u.ops[h - u.start])
            else:
                hands.append(["PASS"])
        row["hands"] = hands
        plan.append(row)
    return plan


def _order_sells(out, prices):
    """Market-order SLOT is a hard price ladder: `_process_market` walks
    slot 0 of BOTH players to exhaustion, reprices, then slot 1. The seat
    whose order sits in the earlier slot takes the top of the curve and
    leaves the walked-down remainder to the other. Measured against
    v43.0_bandit: it puts 84% of its sells in slot 0 and we spread ours
    over slots 0-9, so it out-priced us on every product we both sell
    (STRAWBERRY $145 vs $99, MELON $242 vs $169, FERTILIZER $63 vs $48).
    Sorting our own queue by the dollars at stake puts the biggest order
    where it can still win the collision."""
    mode = int(GENOME.get("sell_order", 0) or 0)
    if mode == 1:                       # biggest dollar order first
        return sorted(out, key=lambda o: -(float(prices.get(o[1], 1) or 1)
                                           * int(o[2])))
    if mode == 2:                       # explicit race order
        # MELON and FERTILIZER are the only two products with (near) ZERO
        # town demand -- FERTILIZER is in no shop and not a town-centre
        # product at all, MELON is in no shop and the centre eats 1/day --
        # so every unit either seat ever sells stays in the inventory for
        # the rest of the season and the price only ever falls. They are
        # one-shot pools split by WHO SELLS FIRST, and this seat currently
        # loses both (MELON $169 vs $242, FERTILIZER $48 vs $63).
        prio = list(GENOME.get("sell_prio") or ())
        rank = dict((p, i) for i, p in enumerate(prio))
        return sorted(out, key=lambda o: (rank.get(o[1], len(prio)),
                                          -(float(prices.get(o[1], 1) or 1)
                                            * int(o[2]))))
    return out


def _fresh_sells(d, farm, priv, prices=None):
    """Market-only refresh: whatever the shed holds right now, at the live
    price. Oversized SELLs partial-fill, so an overlap with the dawn queue
    costs a queue slot at most."""
    g = GENOME
    prices = prices or {}
    shed = {}
    for k, v in (_get(priv, "shed", {}) or {}).items():
        shed[k] = int(v or 0)
    tiles = _get(farm, "tiles", []) or []
    n_beasts = sum(shed.get(s, 0) for s in ANIMALS)     # awaiting a pen
    for row in tiles:
        for tl in row:
            if isinstance(tl, dict) and "animal" in tl:
                n_beasts += 1
    sell_all = d >= LAST_DAY - 1
    reserve_w = 0 if not n_beasts or sell_all else \
        n_beasts + int(g.get("feed_buffer", 6))
    caps = dict(g.get("sell_cap") or {})
    hold = dict(g.get("hold_price") or {})
    total = sum(shed.values())
    pressed = total > int(g.get("valve_hi", 55))
    out = []
    for item in SELLABLE:
        have = shed.get(item, 0)
        if item == "WHEAT" and not sell_all:
            have -= reserve_w
        elif item == "FERTILIZER" and not sell_all:
            have -= int(g.get("fert_keep", 12))
        if have <= 0:
            continue
        # HOLD-WHEN-WORTHLESS. Selling a unit at $1 banks $1 and, by the
        # engine's own rule ("sales at $1 do not increase market supply"),
        # does not even cost the other seat anything. The shed cap and the
        # dusk discard are the only reasons to sell into a floored market,
        # so the hold is released under valve pressure and in liquidation.
        if not sell_all and not pressed:
            hp = float(hold.get(item, 0) or 0)
            if hp > 0 and float(prices.get(item, BASE_PRICE.get(item, 1))) < hp:
                continue
        q = have if sell_all else min(have, int(caps.get(item, 999)))
        if q > 0:
            out.append(["SELL", item, q])
    return _order_sells(out, prices)


def _fallback_agent(obs, cfg=None):
    try:
        d = _get(obs, "day", None)
        h = _get(obs, "hour", None)
        if d is None or h is None:
            step = int(_get(obs, "step", 0) or 0)
            d, h = step // TPD, step % TPD
        d, h = int(d), int(h)
        me = int(_get(obs, "player", 0) or 0)
        farms = _get(obs, "farms", []) or []
        farm = farms[me] if me < len(farms) else {}
        opp = farms[1 - me] if (1 - me) < len(farms) else {}
        priv = _get(obs, "private", {}) or {}
        mkt = _get(obs, "market", {}) or {}
        town = _get(obs, "town", {}) or {}
        if _D["day"] != d or _D["plan"] is None:
            _D["plan"] = _plan(d, farm, priv, mkt, town, opp)
            _D["day"] = d
        a = _D["plan"][h] if h < len(_D["plan"]) else None
        if a is None:
            a = {"farmer": ["PASS"], "hands": [], "market": []}
        market = list(a.get("market") or [])
        if h > 0:
            keep = [o for o in market if o and o[0] != "SELL"]
            market = keep + _fresh_sells(
                d, farm, priv, dict(_get(mkt, "prices", {}) or {}))
        real = _get(farm, "hands", []) or []
        hands = list(a.get("hands") or [])
        if len(hands) < len(real):
            hands += [["PASS"]] * (len(real) - len(hands))
        elif len(hands) > len(real):
            hands = hands[:len(real)]
        return {"farmer": a.get("farmer") or ["PASS"], "hands": hands,
                "market": market[:10]}
    except Exception:
        n = 0
        try:
            farms = _get(obs, "farms", []) or []
            me = int(_get(obs, "player", 0) or 0)
            if me < len(farms):
                n = len(_get(farms[me], "hands", []) or [])
        except Exception:
            n = 0
        return {"farmer": ["PASS"], "hands": [["PASS"]] * n, "market": []}


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        raise SystemExit(_selftest())
