"""Package one seat of a Kaggle replay as a verbatim tape opponent.

Our planner's archetype genes cannot express the day-10 purse of the "class A"
wheat clones that take half our Kaggle games, so we cannot train against a
reconstruction of them.  We can, however, train against the *recording*: a
packaged agent that emits the opponent's per-turn action dict from a replay,
indexed by the engine's step counter.  The immutable kagg2
(../kaggriculture2/main.py) is exactly this and earns ~170k on this engine, so
a fixed action sequence is known to survive replay here.

Why a positional tape transfers across seeds at all: every farm starts
identical -- a 10x10 board whose NW quadrant is empty (`null`) and whose other
three quadrants are `LOCKED`, farmer at (4, 4), no terrain variety -- and both
seats get the same layout.  The seed randomises the *town* (which shops unlock,
in what order), the weed spawns, and therefore the prices, but not a single
tile coordinate the tape names.  What the tape cannot carry over is money: its
SELL revenue depends on prices that our seat also moves, so a HIRE or BUY that
cleared in the original may be refused here, and the engine silently drops it.

Only two runtime repairs are made by default, both of them kagg2's:

  * hands are padded/truncated to the seat's live hand count, because a refused
    HIRE shortens the roster.  (The engine does not reject the action: an
    out-of-range unit order is a silent per-unit no-op -- `_farmer_position`
    returns None and `_apply_unit_action` returns, kaggriculture.py:282/907 --
    so the truncation costs the tape the tail of its crew's orders, it does not
    save the turn from being thrown away.  Measured 2026-09-14.);
  * a step past the end of the tape emits PASS rather than raising.

`--hire-sticky` bakes in a third, OPT-IN repair (`TAPE_HIRE_STICKY=0/1` wins at
run time; the KAGG3_ namespace is cleared for file agents, so the name carries
no prefix).  A refused HIRE is re-issued on the following turns of the same day
until the roster matches the source episode's roster at that step, and hand
orders are addressed by SOURCE hand index through a live->source map instead of
by position.  With the flag off the emitted agent is byte-for-byte the frozen
tape and plays the identical game -- `--from-main` re-cuts an existing package
in the new mode and refuses to write unless that equivalence is proved.

`--hire-sticky-purse` (`TAPE_PURSE_FIX=0/1`) is a fifth, OPT-IN repair, also
hire-sticky-only: the owed-hire re-issue is retried at EVERY later hour of the
same day, including the day's last hour (plain hire-sticky blacks that hour out
because `_src_hands(step + 1)` is already the next day's empty roster), capped
at the source's roster at THAT hour.  It is never carried across midnight: the
engine wipes the roster nightly (kaggriculture.py:880-882), so a hire deferred
past midnight is a different hire and the next day's owed list is recomputed
from the source's own roster.  Measured 2026-09-14 -- it is a no-op on TOPB3,
where hire-sticky already lands 286/286 of the source's hires on every board
(docs/strategy/2026-09-14-tape-purse.md).

`--hire-sticky-remap` (`TAPE_MAP_FIX=0/1`) is a fourth, OPT-IN repair that only
changes hire-sticky runs: the live->source hand map is re-derived every turn, so
a live hand hired AHEAD of the source claims the source's next new hand instead
of PASSing for the rest of the day.  Without it the map is a persistent day-level
assignment and source order k is executed by live hand k+1 from the moment the
seat out-hires its source -- measured on three TOPB3 boards 2026-09-14, worth
-0.35 retention on episode 108741964 (docs/strategy/2026-09-14-tape-map.md).

Usage:
    python scripts/tape_opponent.py <replay.json> [--opponent-team NAME | --seat N]
        -o dist/opponent_tape_<episode>.tar.gz --out-dir <dir>

`--out-dir` writes the same `main.py` unpacked, which is what the eval harness
wants (`--opponents <dir>/main.py`); no tar tooling is needed to use it.
"""

from __future__ import annotations

import argparse
import base64
import gzip
import io
import json
import os
import sys
import tarfile
import zlib
from pathlib import Path

# kaggle_environments takes the **last callable defined in the module
# namespace** as the agent, so `agent` stays the final definition below.
MAIN_TEMPLATE = '''"""Tape opponent: episode {episode}, seat {seat} ({team}).

Generated by scripts/tape_opponent.py -- do not hand-edit.  This is not a
policy: it replays {n} recorded action dicts verbatim, indexed by the engine's
step counter.  In its source episode this seat finished on {final_money} coins
against {opp_team}.

The only runtime adaptation is hand alignment: a HIRE the tape made may be
refused here (prices, and therefore money, differ from the recording), which
leaves the roster shorter than the one the recorded orders were written for.
HIRE-STICKY MODE below is a second, opt-in adaptation; it is off unless
_HIRE_STICKY_DEFAULT is True or TAPE_HIRE_STICKY says otherwise.
"""

import base64
import json
import os
import zlib

#: {n} action dicts, tape[s] = the action this seat took at engine step s.
_TAPE = json.loads(zlib.decompress(base64.b85decode(
    "{blob}"
)).decode("utf-8"))

_EPISODE = {episode}
_SOURCE_SEAT = {seat}
_SOURCE_TEAM = {team!r}
_SOURCE_MONEY = {final_money}

#: The TOWN this seat actually played in: `[day, "SHOP_NAME"]` for each shop the
#: town unlocked, `day` being the first day the shop is visible. Empty unless
#: the tape was cut with `--with-town`.
#:
#: The tape is open-loop but the recorded player was not: it planted for the
#: shops that unlocked in ITS game. Replayed under a freshly drawn town it farms
#: for the wrong buyers, which flatters whoever it is replayed against. Nothing
#: in this file reads `_TOWN` -- the agent's actions are fixed either way -- it
#: is here so the harness that runs the tape can pin the same town:
#: `scripts/town_inject.py` (engine) and `es.tape_actions` -> `sim.eod`
#: (simulator) both read it.
_TOWN = {town!r}

#: Baked in by `scripts/tape_opponent.py --hire-sticky`; TAPE_HIRE_STICKY=0/1
#: wins at run time.  See HIRE-STICKY MODE below.
_HIRE_STICKY_DEFAULT = {hire_sticky}

#: Baked in by `scripts/tape_opponent.py --hire-sticky-remap`; TAPE_MAP_FIX=0/1
#: wins at run time.  Only read when HIRE-STICKY MODE is on.  See `_settle`.
_MAP_FIX_DEFAULT = {map_fix}

#: Baked in by `scripts/tape_opponent.py --hire-sticky-purse`; TAPE_PURSE_FIX=0/1
#: wins at run time.  Only read when HIRE-STICKY MODE is on.  See `_purse_fix_on`.
_PURSE_FIX_DEFAULT = {purse_fix}

#: Source-episode roster size at each step: `len(action["hands"])` is exactly the
#: number of hands the recorded seat had when it computed that action (checked
#: 719/719 steps on episode 108795516 against its ListEpisodes dump), so the
#: tape already carries the roster it is trying to reproduce -- no re-cut of the
#: blob is needed to know it.
_SRC_HANDS = [len(f.get("hands") or []) for f in _TAPE]


def _get(obs, key, default=None):
    if isinstance(obs, dict):
        return obs.get(key, default)
    getter = getattr(obs, "get", None)
    if callable(getter):
        return getter(key, default)
    return getattr(obs, key, default)


def _step(obs):
    """Engine step index for this call.

    `step` is on the shared observation, but only the first seat's copy carries
    it in a serialised replay, so fall back to the per-seat day/hour pair --
    they are the same counter (`step == day * turnsPerDay + hour`, verified on
    the replays this tape was cut from).
    """
    explicit = _get(obs, "step")
    if explicit is not None:
        return int(explicit)
    return int(_get(obs, "day", 0) or 0) * 24 + int(_get(obs, "hour", 0) or 0)


def _farm(obs):
    """This seat's public farm dict (money, hands, hires_today) or an empty one."""
    seat = 1 if int(_get(obs, "player", 0) or 0) == 1 else 0
    farms = list(_get(obs, "farms", []) or [])
    return farms[seat] if seat < len(farms) else {{}}


def _hand_count(obs):
    return len(list(_get(_farm(obs), "hands", []) or []))


def _align(action, hands_wanted):
    hands = [list(order or ["PASS"]) for order in (action.get("hands") or [])]
    hands = hands[:hands_wanted]
    hands.extend([["PASS"]] * (hands_wanted - len(hands)))
    return {{
        "farmer": list(action.get("farmer") or ["PASS"]),
        "hands": hands,
        "market": [list(order) for order in (action.get("market") or [])],
    }}

#__HIRE_FIX__

# NOTE: must remain the LAST callable defined in the module -- the loader picks
# the final callable in the exec namespace as the agent.
def agent(observation, configuration=None):
    step = _step(observation)
    if _hire_sticky_on():
        return _hire_sticky_agent(observation, configuration, step)
    frame = _TAPE[step] if 0 <= step < len(_TAPE) else {{}}
    return _align(frame, _hand_count(observation))
'''

# Spliced in verbatim AFTER `.format()`, so its braces need no doubling.
HIRE_FIX_CODE = '''
# ---------------------------------------------------------- HIRE-STICKY MODE
#
# What goes wrong with the frozen tape (measured 2026-09-14 on episode
# 108795516, the worst TOPB3 board, retention 0.00):
#
#   * `_do_hire` (kaggriculture.py:702) is `if farm["money"] < cost: return` --
#     a HIRE the purse cannot pay for is dropped in silence, and `hires_today`
#     is not incremented, so the tape never learns it is a hand short.
#   * `hands` is append-only within a day and wiped every night
#     (kaggriculture.py:880-882), so source hand index i is simply "the i-th
#     hire that landed today".
#   * `_apply_unit_action` no-ops on an out-of-range unit (`pos is None`,
#     kaggriculture.py:282/907) -- an over-long `hands` list is NOT rejected as
#     illegal; the damage is that the roster is SHORT, so the tape's crew does
#     not do the day's work, revenue falls, and the next day it can afford even
#     fewer hires.  On 108795516 the seat is on 0 coins from day 7 and hires
#     nothing at all on days 21-23.
#
# This mode restores the one reflex the recording had and the tape does not: it
# keeps hiring until its roster matches the roster the source had at the same
# step, and never past it.
#
#   * the tape's own market orders are left untouched (queue order and the
#     `maxMarketOrdersPerTurn` truncation are part of the recording);
#   * `["HIRE"]` is APPENDED, after them, once per owed hand, capped at
#     `_SRC_HANDS[step + 1] - live` so the roster can never overshoot the
#     source's -- appending puts the re-issue behind this turn's SELLs, which
#     is the cash that pays for it;
#   * the owed list is cleared at the day boundary: the engine wipes the roster
#     every night, so a hire deferred past midnight is a different hire;
#   * hand orders are addressed through `_MAP`, live hand index -> source hand
#     index, and a live hand with no source hand to impersonate PASSes -- only
#     that hand's order is dropped, never the turn.
#
# NOTE on `_MAP`: because source hires only ever append, and an owed hand is
# always filled from the lowest unassigned source index, `_MAP` reduces to the
# identity on every path the engine can produce -- i.e. the existing
# `_align` truncation was already the right hand-identity assignment, and the
# index shift is not the defect.  The map is kept explicit anyway: it is what
# makes "source index" the addressing scheme rather than a coincidence, and it
# is what turns an unresolvable reference into one PASS instead of a wrong
# order.

#: Reset per episode: the loader keeps one module image per worker process and
#: replays many games through it, so a step that does not follow the last one
#: means a new game.
_STATE = {"step": -1, "live": 0, "map": [], "owed": []}

#: Instrumentation, OFF unless TAPE_MAP_DEBUG names a directory.  Pure
#: observation -- it reads `_STATE` and writes a jsonl row per step, and
#: changes no action.  One file per (episode, worker pid, replay) so a worker
#: image that plays many games does not interleave them.
_DEBUG = {"run": 0, "claimed": 0}


def _fib(n):
    """kaggriculture.py:690 -- _fib(0)=1, _fib(1)=1, _fib(2)=2, ..."""
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _debug_log(step, turns_per_day, live, frame, extra, farm=None, mult=1):
    """Observation only: never changes an action.

    `TAPE_MAP_DEBUG=<dir>` writes the map-side row (2026-09-14 TAPE-MAP work).
    `TAPE_PURSE_DEBUG=<dir>` writes the same row plus the purse side: the
    seat's `money` and `hires_today` AT THE START OF THE TURN, the cost the
    engine will charge for the next hire this day (`_hire_cost`,
    kaggriculture.py:698), whether that cost is affordable from the opening
    purse, and the op names on the tape's own recorded market row.  Both are
    off unless the variable names a directory.
    """
    out = os.environ.get("TAPE_MAP_DEBUG")
    purse = os.environ.get("TAPE_PURSE_DEBUG")
    if not out and not purse:
        return
    mapping = list(_STATE["map"])[:live]
    owed = list(_STATE["owed"])
    src_orders = frame.get("hands") or []

    def acting(i):
        return 0 <= i < len(src_orders) and list(src_orders[i] or ["PASS"])[0] != "PASS"

    row = {"step": step, "day": step // turns_per_day, "hour": step % turns_per_day,
           "live": live, "src": _src_hands(step), "src_next": _src_hands(step + 1),
           "pinned": sum(1 for i in mapping if i == -1),
           "owed": len(owed), "owed_acting": sum(1 for i in owed if acting(i)),
           "extra": extra, "claimed": _DEBUG["claimed"], "map": mapping}
    if purse:
        farm = farm if farm is not None else {}
        money = float(_get(farm, "money", 0.0) or 0.0)
        done = int(_get(farm, "hires_today", 0) or 0)
        cost = mult * _fib(done)
        row.update(money=money, hires_today=done, cost=cost,
                   afford=bool(money >= cost), short=max(0.0, cost - money),
                   ops=[str(list(o or ["PASS"])[0]) for o in (frame.get("market") or [])],
                   own_hire=sum(1 for o in (frame.get("market") or [])
                                if list(o or ["PASS"])[0] == "HIRE"))
    for d, tag in ((out, "map"), (purse, "purse")):
        if not d:
            continue
        path = "%s/%s_%d_%d_%d.jsonl" % (d, tag, _EPISODE, os.getpid(), _DEBUG["run"])
        with open(path, "a") as fh:
            print(json.dumps(row), file=fh)


def _hire_sticky_on():
    flag = os.environ.get("TAPE_HIRE_STICKY")
    if flag is None or flag == "":
        return _HIRE_STICKY_DEFAULT
    return flag not in ("0", "no", "off", "false", "False")


def _map_fix_on():
    """MAP-REMAP repair, off by default (TAPE_MAP_FIX=1, or --hire-sticky-remap).

    Without it `_MAP` is a *persistent* day-level assignment: a live hand that
    exists before the source had a hand for it to impersonate is pinned to -1
    and PASSes for the REST OF THE DAY, even after the source's own roster
    grows past it and its orders exist again.  That happens whenever the live
    seat lands MORE of the tape's own recorded HIREs in a turn than the source
    did -- the recordings over-submit HIREs and let the fib cost ladder stop
    them, so a seat that is richer at that instant out-hires its source.
    With the repair on, the map is re-derived every turn: an unassigned source
    hand is claimed by the lowest pinned live slot before it is queued as
    `owed`, so a surplus hand follows the source's next new hand instead of
    idling.  Measured 2026-09-14: docs/strategy/2026-09-14-tape-map.md.
    """
    flag = os.environ.get("TAPE_MAP_FIX")
    if flag is None or flag == "":
        return _MAP_FIX_DEFAULT
    return flag not in ("0", "no", "off", "false", "False")


def _purse_fix_on():
    """PURSE repair, off by default (TAPE_PURSE_FIX=1, or --hire-sticky-purse).

    The engine drops a HIRE the purse cannot pay in silence and does NOT
    advance `hires_today` (`_do_hire`, kaggriculture.py:702-705), so the tape
    never learns it is a hand short; hire-sticky already retries the owed hire
    on the following turns of the same day, appended AFTER the tape's own
    market row so the turn's SELL revenue pays for it.  Two hours are missing
    from that retry window:

      * the day's LAST hour, which plain hire-sticky blacks out because its
        room cap reads `_src_hands(step + 1)` -- already the next day's empty
        roster.  With the repair on, the last hour is capped at the source's
        roster at THIS hour instead, so an owed hire gets its final try;
      * nothing else.  A hire owed at midnight is NOT carried over: the engine
        wipes `hands` and `hires_today` every night (kaggriculture.py:880-882),
        the next day's owed list is recomputed from the source's own roster,
        and carrying a debt would let the tape out-hire the seat it is
        impersonating -- the one invariant hire-sticky exists to keep.

    Measured 2026-09-14 (docs/strategy/2026-09-14-tape-purse.md): on all 18
    TOPB3 boards hire-sticky already lands exactly the source's season hire
    count (286/286), so this repair changes no board.  It is kept because it
    closes the last hour of the retry window by construction, and because the
    measurement that it changes nothing is the evidence that the residual
    Majkel1337 divergence is NOT hire-side cash.
    """
    flag = os.environ.get("TAPE_PURSE_FIX")
    if flag is None or flag == "":
        return _PURSE_FIX_DEFAULT
    return flag not in ("0", "no", "off", "false", "False")


def _cfg(configuration, key, default):
    if configuration is None:
        return default
    try:
        return max(1, int(_get(configuration, key, default)))
    except (TypeError, ValueError):
        return default


def _src_hands(step):
    return _SRC_HANDS[step] if 0 <= step < len(_SRC_HANDS) else 0


def _reset():
    _STATE.update(step=-1, live=0, map=[], owed=[])
    _DEBUG["run"] = _DEBUG.get("run", -1) + 1
    _DEBUG["claimed"] = 0


def _settle(step, live):
    """Fold the roster growth the previous step produced into the map."""
    grew = live - _STATE["live"]
    added = list(range(_src_hands(step - 1), _src_hands(step)))
    queue = list(_STATE["owed"]) + added
    mapping = list(_STATE["map"])
    if _map_fix_on():
        # Re-derive: a live hand pinned to -1 earlier today claims the lowest
        # unassigned source hand as soon as one exists, LOWEST SLOT FIRST, so
        # the surplus hand follows the source's next new hand rather than
        # idling for the rest of the day.  Claimed here means not queued as
        # `owed`, so the re-issue never buys a hand we already have.
        _DEBUG["claimed"] = _DEBUG.get("claimed", 0)
        for j, cur in enumerate(mapping):
            if cur == -1 and queue:
                mapping[j] = queue.pop(0)
                _DEBUG["claimed"] += 1
    take = queue[:max(0, grew)]
    _STATE["owed"] = queue[len(take):]
    _STATE["map"] = mapping + take
    if grew > len(take):                      # hired past the source: no identity
        _STATE["map"].extend([-1] * (grew - len(take)))
    _STATE["live"] = live


def _hire_sticky_agent(observation, configuration, step):
    turns_per_day = _cfg(configuration, "turnsPerDay", 24)
    max_orders = _cfg(configuration, "maxMarketOrdersPerTurn", 10)
    farm = _farm(observation)
    live = len(list(_get(farm, "hands", []) or []))
    if step != _STATE["step"] + 1:
        _reset()                              # new episode, or a step we cannot settle
    if step % turns_per_day == 0:             # nightly wipe: kaggriculture.py:880
        _STATE.update(live=live, map=[], owed=[])
    else:
        _settle(step, live)
    _STATE["step"] = step

    frame = _TAPE[step] if 0 <= step < len(_TAPE) else {}
    action = _align(frame, live)
    src_orders = frame.get("hands") or []
    action["hands"] = [list(src_orders[i]) if 0 <= i < len(src_orders) else ["PASS"]
                       for i in _STATE["map"][:live]]
    action["hands"].extend([["PASS"]] * (live - len(action["hands"])))

    # Owed hires, capped at the roster the source reached by the end of this step.
    if (step + 1) % turns_per_day:
        room = _src_hands(step + 1) - live
    elif _purse_fix_on():
        room = _src_hands(step) - live    # last hour of the day: THIS hour's roster
    else:
        room = 0
    extra = max(0, min(len(_STATE["owed"]), room))
    if extra:
        action["market"] = (action["market"] + [["HIRE"]] * extra)[:max_orders]
    _debug_log(step, turns_per_day, live, frame, extra, farm,
               _cfg(configuration, "farmHandCostMult", 1))
    return action

'''


def load_replay(path: Path) -> dict:
    with open(path) as fh:
        return json.load(fh)


def resolve_seat(replay: dict, team: str | None, seat: int | None,
                 ours: str = "OurTeam") -> int:
    """Which seat to tape.

    `--seat` wins; then an exact or case-insensitive-substring team match; then
    the single seat that is not ours, which is the common case (these replays
    are our own losses, so the interesting seat is the other one).
    """
    names = list((replay.get("info") or {}).get("TeamNames") or [])
    if seat is not None:
        if not 0 <= seat < max(2, len(names)):
            raise SystemExit(f"seat {seat} out of range for {names}")
        return seat
    if team is not None:
        for i, name in enumerate(names):
            if name == team:
                return i
        hits = [i for i, name in enumerate(names) if team.lower() in name.lower()]
        if len(hits) == 1:
            return hits[0]
        raise SystemExit(f"--opponent-team {team!r} matched {len(hits)} of {names}")
    hits = [i for i, name in enumerate(names) if name != ours]
    if len(hits) != 1:
        raise SystemExit(f"cannot infer the opponent seat from {names}; pass --seat")
    return hits[0]


def extract_tape(replay: dict, seat: int) -> list[dict]:
    """Actions this seat took, indexed by the engine step they were taken at.

    `steps[t][seat]["action"]` is the action that *produced*
    `steps[t][seat]["observation"]`, so it was computed from the step-(t-1)
    observation and is the action of engine step t-1.  `steps[0]`'s action is
    the loader's placeholder and is dropped.  A refused turn (status INVALID /
    ERROR / TIMEOUT) is recorded as `None`; it becomes a PASS, which is what
    the engine did with it.
    """
    steps = replay["steps"]
    tape = []
    for t in range(1, len(steps)):
        action = steps[t][seat].get("action")
        if not isinstance(action, dict):
            action = {}
        tape.append({
            "farmer": list(action.get("farmer") or ["PASS"]),
            "hands": [list(order or ["PASS"]) for order in (action.get("hands") or [])],
            "market": [list(order) for order in (action.get("market") or [])],
        })
    return tape


def extract_town(replay: dict) -> list:
    """The recorded town schedule as `[[day, "SHOP_NAME"], ...]`.

    `observation["town"]` carries exactly one key, `unlocked_shops`: the list
    the engine appends to in `_end_of_day`, in unlock order, with repeats (shops
    are drawn WITH replacement, so the same name can appear more than once).
    There are no shop-local demand rows in the observation -- a shop's demand is
    a constant of its type (`SHOPS` in the engine, `spec._SHOP_DEMAND` here) --
    so the schedule is the whole of the town's state.

    The list is reduced to one `(day, shop)` per unlock by diffing consecutive
    steps and reading the day off the observation the growth first appears in.
    That day is the engine's `next_day`, i.e. the first day the shop is visible
    and sells; `_end_of_day(day)` appended it at the end of `day - 1`.
    """
    out, prev = [], []
    for step in replay["steps"]:
        obs = step[0]["observation"]
        town = obs.get("town") or {}
        shops = list(town.get("unlocked_shops") or [])
        if len(shops) > len(prev):
            day = int(obs.get("day") or 0)
            for name in shops[len(prev):]:
                out.append([day, str(name)])
        prev = shops
    return out


def load_main(path: Path) -> dict:
    """Recover a tape (and its provenance) from a main.py this script wrote.

    The replays are ~30 MB and stay out of the tree, so re-cutting an existing
    tape in a new mode has to start from the packaged agent, not the source
    episode.  Exec'ing it is exactly how the engine loads it, and `_TOWN` comes
    back with everything else, so a `--with-town` package stays pinned.
    """
    ns: dict = {}
    exec(compile(path.read_text(), str(path), "exec"), ns)  # noqa: S102
    opp = "?"
    for line in (ns.get("__doc__") or "").splitlines():
        if line.startswith("against "):
            opp = line[len("against "):].rstrip(".")
    return {"tape": ns["_TAPE"], "episode": ns["_EPISODE"], "seat": ns["_SOURCE_SEAT"],
            "team": ns["_SOURCE_TEAM"], "final_money": ns["_SOURCE_MONEY"],
            "town": ns.get("_TOWN") or [], "opp_team": opp}


def load_agent(main_py: str, hire_sticky: bool | None = None) -> dict:
    """Exec the emitted file the way kaggle_environments does, with
    TAPE_HIRE_STICKY pinned for the question the caller is asking."""
    if hire_sticky is not None:
        os.environ["TAPE_HIRE_STICKY"] = "1" if hire_sticky else "0"
    ns: dict = {}
    exec(compile(main_py, "<tape>", "exec"), ns)  # noqa: S102
    return ns


def render_main(tape: list[dict], episode: int, seat: int, team: str,
                opp_team: str, final_money: float, town=None,
                hire_sticky: bool = False, map_fix: bool = False,
                purse_fix: bool = False) -> str:
    raw = json.dumps(tape, separators=(",", ":")).encode("utf-8")
    blob = base64.b85encode(zlib.compress(raw, 9)).decode("ascii")
    # b85 has no quote characters, so the blob is safe inside the "..." above;
    # wrap it so the emitted file stays diffable.
    wrapped = '"\n    "'.join(blob[i:i + 92] for i in range(0, len(blob), 92))
    return MAIN_TEMPLATE.format(
        blob=wrapped, n=len(tape), episode=episode, seat=seat, team=team,
        opp_team=opp_team, final_money=int(final_money),
        town=[list(row) for row in (town or [])],
        hire_sticky=bool(hire_sticky), map_fix=bool(map_fix),
        purse_fix=bool(purse_fix),
    ).replace("#__HIRE_FIX__", HIRE_FIX_CODE)


def verify(main_py: str, replay: dict, seat: int) -> int:
    """Feed the emitted agent every recorded pre-state and count disagreements.

    Cheap and fixture-free (the replays are ~30 MB and stay out of the tree),
    and it is the check that actually matters: it catches an off-by-one in the
    step index, which nothing downstream would flag -- a tape shifted by one
    turn still plays a plausible-looking game.
    """
    # exec on purpose: this is exactly how kaggle_environments loads the file,
    # so the check exercises the module the engine will see, not an import of
    # it.  Hire-sticky is forced off: this asks whether the TAPE is right, not
    # what the reflex does with it.
    ns = load_agent(main_py, hire_sticky=False)
    agent, align, hand_count = ns["agent"], ns["_align"], ns["_hand_count"]
    steps = replay["steps"]
    bad = 0
    for t in range(len(steps) - 1):
        obs = dict(steps[t][seat]["observation"])
        obs.setdefault("player", seat)
        want = steps[t + 1][seat].get("action")
        # Compare through the same hand alignment the tape applies: a turn the
        # engine refused is recorded as a null action, and replaying it as PASS
        # for the live roster is the intended behaviour, not a disagreement.
        expected = align(want if isinstance(want, dict) else {}, hand_count(obs))
        if agent(obs) != expected:
            bad += 1
    return bad


def verify_frozen_match(new_main: str, old_main: str, max_hands: int = 14) -> int:
    """Count (step, roster) pairs where the new file, flag off, differs from the old.

    The frozen agent is a pure function of (step, live hand count), so sweeping
    every step against every plausible roster size is an exhaustive equivalence
    proof -- stronger than a replay, and it needs no replay to run.
    """
    new_ns = load_agent(new_main, hire_sticky=False)
    old_ns = load_agent(old_main, hire_sticky=False)
    bad = 0
    for step in range(len(new_ns["_TAPE"]) + 2):
        for hands in range(max_hands + 1):
            obs = {"step": step, "player": 0,
                   "farms": [{"hands": [[0, 0]] * hands}, {"hands": []}]}
            if new_ns["agent"](obs) != old_ns["agent"](obs):
                bad += 1
    return bad


def write_tar(main_py: str, out: Path) -> Path:
    """Deterministic archive: zeroed mtime/uid/gid and a gzip header with
    mtime=0, so two builds of the same replay hash the same (the same contract
    scripts/package_submission.py holds itself to)."""
    out.parent.mkdir(parents=True, exist_ok=True)
    data = main_py.encode("utf-8")
    with open(out, "wb") as raw, gzip.GzipFile(
            filename="", mode="wb", fileobj=raw, compresslevel=9, mtime=0) as gz, \
            tarfile.open(fileobj=gz, mode="w") as tf:
        info = tarfile.TarInfo("main.py")
        info.size = len(data)
        info.mtime = 0
        info.uid = info.gid = 0
        info.uname = info.gname = ""
        info.mode = 0o644
        tf.addfile(info, io.BytesIO(data))
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("replay", type=Path, nargs="?")
    ap.add_argument("--from-main", type=Path,
                    help="re-cut a main.py this script wrote (no replay needed); "
                         "its _TAPE, _TOWN and provenance are carried over")
    ap.add_argument("--opponent-team", help="team name (exact, or a unique substring)")
    ap.add_argument("--seat", type=int, help="seat index; wins over --opponent-team")
    ap.add_argument("--ours", default="OurTeam",
                    help="our team name, used to infer the opponent seat")
    ap.add_argument("-o", "--out", type=Path,
                    help="tar.gz to write (default dist/opponent_tape_<episode>.tar.gz)")
    ap.add_argument("--out-dir", type=Path,
                    help="also write main.py unpacked here, for --opponents <dir>/main.py")
    ap.add_argument("--with-town", action="store_true",
                    help="also record the town this seat played in (the "
                         "per-unlock-day shop list) as the package's `_TOWN` "
                         "constant, for a harness that pins it; off by default, "
                         "and a package cut without it is byte-identical to one "
                         "cut before the flag existed")
    ap.add_argument("--hire-sticky", action="store_true",
                    help="bake in HIRE-STICKY mode: re-issue a refused HIRE on "
                         "the following turns of the same day until the roster "
                         "matches the source episode's, never past it, and "
                         "address hand orders by source hand index "
                         "(TAPE_HIRE_STICKY=0/1 wins at run time)")
    ap.add_argument("--hire-sticky-remap", action="store_true",
                    help="bake in the MAP-REMAP repair on top of HIRE-STICKY: "
                         "re-derive the live->source hand map every turn so a "
                         "live hand hired ahead of the source claims the "
                         "source's next new hand instead of PASSing for the "
                         "rest of the day (TAPE_MAP_FIX=0/1 wins at run time; "
                         "inert unless hire-sticky is on)")
    ap.add_argument("--hire-sticky-purse", action="store_true",
                    help="bake in the PURSE repair on top of HIRE-STICKY: retry "
                         "an owed hire at every later hour of the same day, the "
                         "day's LAST hour included (plain hire-sticky blacks it "
                         "out), capped at the source's roster at that hour and "
                         "never carried across midnight (TAPE_PURSE_FIX=0/1 wins "
                         "at run time; inert unless hire-sticky is on)")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip replaying the tape back over the recorded pre-states")
    args = ap.parse_args(argv)

    if (args.replay is None) == (args.from_main is None):
        raise SystemExit("pass exactly one of <replay.json> or --from-main")

    replay = None
    if args.from_main is not None:
        src = load_main(args.from_main)
        seat, episode, tape = src["seat"], src["episode"], src["tape"]
        names = ([src["team"], src["opp_team"]] if seat == 0
                 else [src["opp_team"], src["team"]])
        final_money, town = src["final_money"], src["town"]
    else:
        replay = load_replay(args.replay)
        seat = resolve_seat(replay, args.opponent_team, args.seat, args.ours)
        names = list((replay.get("info") or {}).get("TeamNames") or ["", ""])
        episode = int((replay.get("info") or {}).get("EpisodeId") or 0)
        tape = extract_tape(replay, seat)
        final_money = replay["steps"][-1][0]["observation"]["farms"][seat]["money"]
        town = extract_town(replay) if args.with_town else None

    main_py = render_main(tape, episode, seat, names[seat], names[1 - seat],
                          final_money, town=town, hire_sticky=args.hire_sticky,
                          map_fix=args.hire_sticky_remap,
                          purse_fix=args.hire_sticky_purse)
    if not args.no_verify:
        if replay is not None:
            bad = verify(main_py, replay, seat)
            if bad:
                raise SystemExit(f"tape disagrees with the replay on {bad}/{len(tape)} steps")
        else:
            # No replay to check against, so check what is actually at stake:
            # with the flag off this file must play the source file's game
            # move for move, at every step and every roster size.
            bad = verify_frozen_match(main_py, args.from_main.read_text())
            if bad:
                raise SystemExit(f"re-cut file differs from {args.from_main} on "
                                 f"{bad} (step, roster) pairs with the flag off")
    out = args.out or Path("dist") / f"opponent_tape_{episode}.tar.gz"
    write_tar(main_py, out)
    if args.out_dir:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        (args.out_dir / "main.py").write_text(main_py)

    acting = sum(1 for f in tape
                 if f["market"] or f["farmer"][0] != "PASS"
                 or any(h[0] != "PASS" for h in f["hands"]))
    print(f"episode {episode} seat {seat} ({names[seat]}) vs {names[1 - seat]}: "
          f"{len(tape)} steps, {acting} acting, {int(final_money)} coins"
          f"{'' if args.no_verify else (', verified' if replay is not None else ', frozen-identical')}"f"{', HIRE-STICKY' if args.hire_sticky else ''}"
          f"{', MAP-REMAP' if args.hire_sticky_remap else ''}"
          f"{', PURSE' if args.hire_sticky_purse else ''}"
          f"{f', town {len(town)} unlocks' if town else ''} -> {out}"
          + (f", {args.out_dir}/main.py" if args.out_dir else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
