"""Stage 3: turn a top-ladder strategy profile into agent parameters.

`replay_analysis.py` gives us what the best agents on the ladder actually do --
how many cows they keep, how many hands they hire, when they buy land. This
module maps those observations onto our `PARAMS` knobs and writes a new,
self-contained agent file `agents/agent_v2_<timestamp>.py`.

Design choice: **blend, don't copy.** The median of a handful of replays is a
noisy estimate, and their numbers come from a different planner than ours -- a
portfolio that works for their code may not work for ours. So each knob moves a
fraction (`learn_rate`) of the way from our current value toward the observed
one, and the search in `tune.py` gets the final say. Copying wholesale reliably
made things worse in testing; blending plus re-tuning did not.

Only knobs with a *direct* observable counterpart are touched. Things like
`feed_runway_days` or `sell_floor` have no visible analogue in a replay and are
left to the tuner.
"""
from kaggriculture.paths import ROOT
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))

import kaggriculture.pipeline.params as paramio  # noqa: E402

# knob  <-  key in the aggregated profile
TILE_TARGETS = {
    "target_wheat": "WHEAT",
    "target_carrot": "CARROT",
    "target_tomato": "TOMATO",
    "target_strawberry": "STRAWBERRY",
    "target_melon": "MELON",
    "target_goose": "GOOSE",
    "target_cow": "COW",
    "target_sheep": "SHEEP",
}


def _blend(current, observed, rate):
    return current + (observed - current) * rate


def derive_params(base_params, top_agg, learn_rate=0.5, notes=None):
    """Return (new_params, list_of_change_descriptions)."""
    p = dict(base_params)
    changes = []
    if not top_agg:
        return p, ["no top-ladder profile available -- parameters unchanged"]

    def apply(knob, observed, lo, hi, label, integer=True):
        cur = p.get(knob)
        if cur is None or observed is None:
            return
        new = _blend(float(cur), float(observed), learn_rate)
        new = max(lo, min(hi, new))
        new = int(round(new)) if integer else round(new, 3)
        if new != cur:
            p[knob] = new
            changes.append(f"{knob}: {cur} -> {new}   (top ladder {label} "
                           f"{observed:.1f}, blended at {learn_rate:g})")

    for knob, asset in TILE_TARGETS.items():
        apply(knob, top_agg["peak_tiles"].get(asset), 0, 60, f"peak {asset} tiles")

    apply("max_herd", top_agg.get("peak_herd"), 4, 60, "peak herd")
    apply("hands_max", top_agg.get("peak_hands"), 2, 24, "peak hands/day")

    # Land timing: only tighten, never delay -- expanding late is strictly worse.
    land_days = [d for d in (top_agg.get("land_days") or []) if d is not None]
    if land_days:
        cur = list(p.get("land_min_day", [0, 2, 5]))
        new = list(cur)
        for i, d in enumerate(land_days[:len(cur)]):
            new[i] = int(min(cur[i], max(0, round(_blend(cur[i], d, learn_rate)))))
        if new != cur:
            p["land_min_day"] = new
            changes.append(f"land_min_day: {cur} -> {new}   "
                           f"(top ladder bought on days {land_days})")

    # If the ladder commits to livestock much earlier than we do, free the cash.
    fad = top_agg.get("first_animal_day")
    if fad is not None and fad <= 3 and p.get("animal_cash_buffer", 0) > 400:
        old = p["animal_cash_buffer"]
        p["animal_cash_buffer"] = int(max(200, old * 0.6))
        changes.append(f"animal_cash_buffer: {old} -> {p['animal_cash_buffer']}   "
                       f"(top ladder places its first animal on day {fad:.0f})")

    if notes:
        changes.extend(notes)
    return p, changes


def write_agent(base_agent, params, out_dir, timestamp=None, provenance=""):
    """Write agents/agent_v2_<timestamp>.py and return its path."""
    ts = timestamp or time.strftime("%Y%m%d_%H%M%S")
    out = os.path.join(out_dir, f"agent_v2_{ts}.py")
    doc = f"""Kaggriculture agent v2 -- replay-refined ({ts}).

GENERATED FILE -- do not hand-edit. Produced by src/kaggriculture/pipeline/pipeline.py:

    top-ladder replays -> src/kaggriculture/data/replay_analysis.py -> src/kaggriculture/train/refine.py
                       -> src/kaggriculture/train/tune.py -> this file

It is agents/v1_heuristic.py's planner with a PARAMS block derived from what
the highest-rated agents on the ladder actually do, then refined by self-play
search. Self-contained: submittable directly as main.py.

{provenance}
"""
    paramio.write(base_agent, out, params,
                  header="Generated by src/kaggriculture/pipeline/pipeline.py -- do not hand-edit.",
                  module_doc=doc)
    return out


def main():
    import argparse
    import json
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--base", default=os.path.join(ROOT, "agents", "v2_tuned.py"))
    ap.add_argument("--profile", required=True, help="aggregated profile JSON")
    ap.add_argument("--learn-rate", type=float, default=0.5)
    ap.add_argument("--out-dir", default=os.path.join(ROOT, "agents"))
    args = ap.parse_args()

    with open(args.profile, encoding="utf-8") as f:
        top = json.load(f)
    base = paramio.load(args.base)
    new, changes = derive_params(base, top, args.learn_rate)
    for c in changes:
        print("  " + c)
    path = write_agent(os.path.join(ROOT, "agents", "v1_heuristic.py"),
                       new, args.out_dir)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
