"""v63.12 Kaggle CPU jobs (K0): one PRIVATE dataset with everything a job needs + one private notebook per job.

    python python/v6312/kjobs.py pack                      # (re)build kaggle/v6312_ds and create/version debmalya84/krl-v6312
    python python/v6312/kjobs.py run NAME "bash commands"  # push notebook krl-v6312-NAME; the commands run in /kaggle/working/w
    python python/v6312/kjobs.py status [NAME ...]
    python python/v6312/kjobs.py fetch NAME                # -> data/kaggle_out/v6312/NAME/

The job sees the repo layout under W=/kaggle/working/w (bin/ = Linux musl binaries, env KRL_RL=W, KRL_BIN=W/bin,
KRL_SELFPLAY=W/bin/selfplay) and writes results to W/out/, which is copied to /kaggle/working/out/.
Everything is private: kjob.make_kernel refuses anything else, and the dataset is created without --public.
"""
import json
import os
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import kjob  # noqa: E402

RL = kjob.RL
DS_DIR = os.path.join(RL, "kaggle", "v6312_ds")
DS_ID = f"{kjob.OWNER}/krl-v6312"
LBIN = os.path.join(RL, "target-linux", "x86_64-unknown-linux-musl", "release")
BINS = ["selfplay", "tapeplay", "endg-label", "ppo-rollout", "agent-stdio", "gt-label"]
RELEASES = ["v63.6_rl", "v63.7_rl", "v63.8_rl", "v63.10_rl", "v63.11_rl"]
PPO_RUN = "weights/ppo/ppo-gru64-f2-p36-from-init-20260926T0344Z"
COPY = ["configs", "python", "weights/v6312", "data/worlds/w64_bank.json", "weights/endg", "weights/release/v63.11_rl", "weights/bc",
        "data/tapes/leaders", f"{PPO_RUN}/ckpt.pt", f"{PPO_RUN}/best.pt", f"{PPO_RUN}/snapshots/i000910.bin"]
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc")


def pack():
    shutil.rmtree(DS_DIR, ignore_errors=True)
    os.makedirs(os.path.join(DS_DIR, "bin"))
    for b in BINS:
        shutil.copy(os.path.join(LBIN, b), os.path.join(DS_DIR, "bin", b))
    for r in RELEASES:
        shutil.copytree(os.path.join(RL, "data", "builds", r, "stage"), os.path.join(DS_DIR, "data", "builds", r, "stage"), ignore=IGNORE)
    for p in COPY + sys.argv[2:]:
        s, d = os.path.join(RL, p), os.path.join(DS_DIR, p)
        os.makedirs(os.path.dirname(d), exist_ok=True)
        (shutil.copytree(s, d, ignore=IGNORE) if os.path.isdir(s) else shutil.copy(s, d))
    json.dump({"title": "krl-v6312", "id": DS_ID, "licenses": [{"name": "CC0-1.0"}]},
              open(os.path.join(DS_DIR, "dataset-metadata.json"), "w"), indent=1)
    rc, out = kjob.kaggle(["datasets", "status", DS_ID])
    if "ready" in out.lower() or "pending" in out.lower():
        rc, out = kjob.kaggle(["datasets", "version", "-p", DS_DIR, "-m", "v63.12 " + kjob.now(), "-r", "zip", "-q"], timeout=3600)
    else:
        rc, out = kjob.kaggle(["datasets", "create", "-p", DS_DIR, "-r", "zip", "-q"], timeout=3600)
    print(rc, out.strip()[-400:])
    for _ in range(90):
        rc, st = kjob.kaggle(["datasets", "status", DS_ID])
        if "ready" in st.lower():
            print("dataset ready")
            return
        time.sleep(20)
    print("dataset not ready yet:", st.strip())


TEMPLATE = r'''# krl-v6312 job __NAME__ (generated by python/v6312/kjobs.py)
import datetime, glob, json, os, shutil, subprocess, time
T0 = time.time()
W = '/kaggle/working/w'
src = os.path.dirname(sorted(glob.glob('/kaggle/input/**/bin/selfplay', recursive=True))[0])
root = os.path.dirname(src)
shutil.copytree(root, W, dirs_exist_ok=True)
for b in glob.glob(W + '/bin/*'):
    os.chmod(b, 0o755)
os.makedirs(W + '/out', exist_ok=True)
env = dict(os.environ, KRL_RL=W, KRL_BIN=W + '/bin', KRL_SELFPLAY=W + '/bin/selfplay', KRL_ROLL=W + '/bin/ppo-rollout', PYTHONUNBUFFERED='1')
p = subprocess.Popen(['bash', '-c', __CMD__], cwd=W, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
log = open(W + '/out/job.log', 'w')
for line in p.stdout:
    print(line, end='', flush=True); log.write(line); log.flush()
rc = p.wait()
shutil.copytree(W + '/out', '/kaggle/working/out', dirs_exist_ok=True)
files = sorted(os.path.relpath(f, '/kaggle/working') for f in glob.glob('/kaggle/working/out/**', recursive=True) if os.path.isfile(f))
open('/kaggle/working/out/manifest.txt', 'w').write('\n'.join(files + ['out/manifest.txt']) + '\n')
json.dump({'rc': rc, 'secs': round(time.time() - T0, 1), 'name': '__NAME__',
           'finished_utc': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}, open('/kaggle/working/run.json', 'w'))
shutil.rmtree(W, ignore_errors=True)
print('RC', rc, 'secs', round(time.time() - T0, 1), flush=True)
'''


def run(name, cmd):
    k = f"krl-v6312-{name}"
    code = TEMPLATE.replace("__NAME__", name).replace("__CMD__", repr(cmd))
    kjob.make_kernel(k, [DS_ID], code)
    t = kjob.push(k)
    st = json.load(open(STATE)) if os.path.exists(STATE) else {}
    st[name] = {"kernel": k, "pushed": t, "cmd": cmd}
    json.dump(st, open(STATE, "w"), indent=1)


STATE = os.path.join(RL, "data", "kaggle_out", "v6312_state.json")


def status(names):
    st = json.load(open(STATE)) if os.path.exists(STATE) else {}
    for n in names or sorted(st):
        print(n, kjob.status(f"krl-v6312-{n}"), st.get(n, {}).get("pushed", ""))


def fetch(name):
    dest = os.path.join(RL, "data", "kaggle_out", "v6312", name)
    os.makedirs(dest, exist_ok=True)
    rc, out = kjob.kaggle(["kernels", "output", f"{kjob.OWNER}/krl-v6312-{name}", "-p", dest, "--force"], timeout=1800)
    print(rc, out.strip()[-300:])


if __name__ == "__main__":
    c = sys.argv[1]
    if c == "pack":
        pack()
    elif c == "run":
        run(sys.argv[2], sys.argv[3])
    elif c == "status":
        status(sys.argv[2:])
    elif c == "fetch":
        fetch(sys.argv[2])
