# Kaggriculture RL -- policy GATE for one candidate (generated by python/gate_kaggle.py; do not hand-edit the pushed copy).
# Runs python/learn/gate.py (shipped in the private weights dataset) with the static Linux ppo-rollout
# (debmalya84/kaggriculture-rl-bin): the candidate's greedy policy and v61.1 play the same validation
# seeds against the Rust panel; writes /kaggle/working/gates/<candidate>__<UTC>.json + manifest + run.json.
import datetime, glob, json, os, shutil, subprocess, time
T0 = time.time()
NAME = __NAME__
WFILE = __WFILE__
N = __N__
THREADS = __THREADS__
W = '/kaggle/working/w'
for d in ('configs/bases/v61.1', 'configs/profiles', 'data/gates', 'bin'):
    os.makedirs(os.path.join(W, d), exist_ok=True)
b = os.path.dirname(sorted(glob.glob('/kaggle/input/**/ppo-rollout', recursive=True))[0])
shutil.copy(b + '/ppo-rollout', W + '/bin/ppo-rollout'); os.chmod(W + '/bin/ppo-rollout', 0o755)
shutil.copy(b + '/v611_router.json', W + '/configs/bases/v61.1/router.json')
shutil.copy(b + '/v611_routes.json', W + '/configs/bases/v61.1/routes.json')
shutil.copy(b + '/profiles_v2.json', W + '/configs/profiles/v2.json')
wd = os.path.dirname(sorted(glob.glob('/kaggle/input/**/gate.py', recursive=True))[0])
weights = os.path.join(wd, WFILE)
assert os.path.exists(weights), weights
env = dict(os.environ, KRL_RL=W, KRL_ROLL=W + '/bin/ppo-rollout')
cmd = ['python', wd + '/gate.py', 'tournament', '--cands', f'{NAME}={weights}', '--n', str(N), '--threads', str(THREADS)]
print(' '.join(cmd), flush=True)
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=env, cwd=W)
for line in p.stdout:
    print(line, end='', flush=True)
rc = p.wait()
os.makedirs('/kaggle/working/gates', exist_ok=True)
for f in glob.glob(W + '/data/gates/*.json'):
    if 'tournament' not in os.path.basename(f):
        shutil.copy(f, '/kaggle/working/gates/')
files = sorted(os.path.relpath(f, '/kaggle/working') for f in glob.glob('/kaggle/working/gates/*.json'))
open('/kaggle/working/gates/manifest.txt', 'w').write('\n'.join(files + ['gates/manifest.txt']) + '\n')
json.dump({'rc': rc, 'secs': round(time.time() - T0, 1), 'name': NAME, 'n': N,
           'finished_utc': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')},
          open('/kaggle/working/run.json', 'w'), indent=1)
shutil.rmtree(W, ignore_errors=True)
print('RC', rc, 'secs', round(time.time() - T0, 1), flush=True)
assert rc == 0, 'gate failed'
