"""Kaggriculture submission: the Rust port of v61.x behind a stdio bridge.

Tarball layout (main.py at the archive root):
    main.py            this file (pure stdlib)
    agent-stdio        the compiled Linux x86_64 (musl, static) agent
    base/              routes.json + router.json (the base agent's route tables)
    profiles.json      the lever-profile table
    fallback.py        the Python v61.1 agent (same policy; used only if the binary fails)

The binary is spawned once per episode (found relative to __file__) and answers one observation
JSON per line with one action JSON. The market list is passed through UNCHANGED: empty `[]` orders
and zero-quantity SELLs are deliberate -- they hold positional slots in the engine's lockstep
market race. Any failure (spawn, crash, timeout, malformed reply) retires the binary for the
episode and the Python v61.1 plays on. agent() never raises.

Generated by scripts/build_submission.ps1 -- settings below are filled in there.
"""
import json
import os
import subprocess
import sys
import threading
import time

PROFILE = __PROFILE__            # fixed profile id, or None
CLONE_PROFILE = __CLONE_PROFILE__  # clone-gated controller target profile, or None
CLONE_STRICT = __CLONE_STRICT__    # strict clone gate (positions + similarity, no cash mirror)
POLICY = __POLICY__                # learned macro policy weights file in the tarball (e.g. "policy.bin"), or None
BUILD = "__BUILD__"

# First turn = spawn + 4.8 MB route-table load + turn: ~0.28 s measured in the Linux harness
# container. A first turn past actTimeout draws on remainingOverageTime (60 s), it does not time
# the agent out, so a generous watchdog here only protects against a hung binary.
FIRST_BUDGET = 5.0
TURN_BUDGET = 0.25    # measured worst turn ~12 ms on this box; actTimeout is 1.0 s

STATS = {"turns": 0, "bridge": 0, "fallback": 0, "timeouts": 0, "bad_reply": 0, "worst_ms": 0.0,
         "reason": "", "build": BUILD, "profile": PROFILE, "clone_profile": CLONE_PROFILE, "clone_strict": CLONE_STRICT, "policy": POLICY}
_BIN = {"proc": None, "q": None, "dead": False, "started": False}
_FB = {"fn": None}
# Kaggle's loader exec()s this file WITHOUT defining __file__ (found 2026-09-25 by the private
# notebook's self-check: `HERE = dirname(__file__)` at import raised NameError and the agent never
# loaded). The directory is resolved at the first call instead, from (in order) __file__ if present,
# the loader's configuration["__raw_path__"], /kaggle_simulations/agent, and the working directory.
_ROOTS = []


def _roots(cfg=None):
    if _ROOTS:
        return _ROOTS
    cands = []
    f = globals().get("__file__")
    if f:
        cands.append(os.path.dirname(os.path.abspath(f)))
    try:
        raw = cfg.get("__raw_path__") if hasattr(cfg, "get") else None
    except Exception:  # noqa: BLE001
        raw = None
    if isinstance(raw, str) and len(raw) < 4096 and "\n" not in raw:
        cands.append(os.path.dirname(os.path.abspath(raw)))
    cands += ["/kaggle_simulations/agent", os.getcwd()]
    for c in cands:
        if c and c not in _ROOTS:
            _ROOTS.append(c)
    return _ROOTS


def _find(name, cfg=None):
    for root in _roots(cfg):
        for n in (name, name + ".exe"):
            p = os.path.join(root, n)
            if os.path.exists(p):
                return p, root
    return None, None


def _reader(pipe, q):
    try:
        for line in pipe:
            q.append(line)
    except Exception:
        pass
    finally:
        q.append(None)


def _spawn(cfg=None):
    _BIN["started"] = True
    path, root = _find("agent-stdio", cfg)
    if not path:
        _BIN["dead"] = True
        STATS["reason"] = "binary not found"
        return
    try:
        if not os.access(path, os.X_OK):
            try:
                os.chmod(path, 0o755)
            except OSError:
                pass
        cmd = [path, "--base", os.path.join(root, "base")]
        prof = os.path.join(root, "profiles.json")
        if os.path.exists(prof) and (PROFILE is not None or CLONE_PROFILE is not None or POLICY is not None):
            cmd += ["--profiles", prof]
            if PROFILE is not None:
                cmd += ["--profile", str(PROFILE)]
            if POLICY is not None and os.path.exists(os.path.join(root, POLICY)):
                cmd += ["--policy", os.path.join(root, POLICY)]
            if CLONE_PROFILE is not None:
                cmd += ["--clone-profile", str(CLONE_PROFILE)]
                if CLONE_STRICT:
                    cmd += ["--clone-strict"]
        proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                                text=True, encoding="utf-8", bufsize=1, cwd=root)
    except Exception as exc:  # noqa: BLE001
        _BIN["dead"] = True
        STATS["reason"] = "spawn: %s" % (exc,)
        return
    q = []
    threading.Thread(target=_reader, args=(proc.stdout, q), daemon=True).start()
    _BIN["proc"], _BIN["q"] = proc, q


def _kill(reason):
    _BIN["dead"] = True
    STATS["reason"] = STATS["reason"] or reason
    proc, _BIN["proc"], _BIN["q"] = _BIN["proc"], None, None
    if proc is not None:
        try:
            proc.kill()
        except Exception:  # noqa: BLE001
            pass


def _ask(payload, budget):
    proc, q = _BIN["proc"], _BIN["q"]
    if proc is None or q is None:
        return None
    try:
        proc.stdin.write(payload + "\n")
        proc.stdin.flush()
    except Exception:  # noqa: BLE001
        _kill("stdin write failed")
        return None
    deadline = time.time() + budget
    while not q:
        if time.time() > deadline:
            STATS["timeouts"] += 1
            _kill("turn exceeded %.2fs" % budget)
            return None
        if proc.poll() is not None:
            _kill("process exited rc=%s" % proc.poll())
            return None
        time.sleep(0.0002)
    line = q.pop(0)
    if line is None:
        _kill("stdout closed")
        return None
    try:
        reply = json.loads(line)
    except Exception:  # noqa: BLE001
        STATS["bad_reply"] += 1
        _kill("malformed reply")
        return None
    return reply if isinstance(reply, dict) else None


def _plain(o):
    if isinstance(o, dict):
        return dict((str(k), _plain(v)) for k, v in o.items())
    if isinstance(o, (list, tuple)):
        return [_plain(v) for v in o]
    if isinstance(o, (str, int, float, bool)) or o is None:
        return o
    return str(o)


def _n_hands(obs):
    try:
        return len(obs["farms"][int(obs["player"])]["hands"] or [])
    except Exception:  # noqa: BLE001
        return 0


def _shape(action, n_hands):
    """Structural sanity only: farmer a list, hands aligned positionally, at most 10 orders.
    Market entries (incl. [] holes and zero quantities) are passed through untouched."""
    if not isinstance(action, dict):
        return None
    farmer = action.get("farmer")
    farmer = farmer if isinstance(farmer, list) and farmer else ["PASS"]
    hands = action.get("hands")
    hands = [h if isinstance(h, list) and h else ["PASS"] for h in (hands if isinstance(hands, list) else [])]
    hands = (hands + [["PASS"]] * n_hands)[:n_hands]
    market = action.get("market")
    market = [o for o in market if isinstance(o, list)][:10] if isinstance(market, list) else []
    return {"farmer": farmer, "hands": hands, "market": market}


def _fallback(obs, cfg):
    if _FB["fn"] is None:
        import importlib.util
        path, _ = _find("fallback.py", cfg)
        spec = importlib.util.spec_from_file_location("v611_fallback", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        fns = [v for v in vars(mod).values() if callable(v)]
        _FB["fn"] = getattr(mod, "agent", None) or fns[-1]
    return _FB["fn"](obs, cfg)


def _beacon(tag):
    try:
        sys.stderr.write("RUSTV61 %s %s\n" % (tag, json.dumps(STATS)))
        sys.stderr.flush()
    except Exception:  # noqa: BLE001
        pass


def agent(obs, cfg=None):
    t0 = time.time()
    STATS["turns"] += 1
    action = None
    try:
        if not _BIN["started"]:
            _spawn(cfg)
        if not _BIN["dead"]:
            try:
                payload = json.dumps(obs, separators=(",", ":"))
            except Exception:  # noqa: BLE001
                payload = json.dumps(_plain(obs), separators=(",", ":"))
            reply = _ask(payload, FIRST_BUDGET if STATS["bridge"] == 0 else TURN_BUDGET)
            if reply is not None:
                action = _shape(reply, _n_hands(obs))
        if action is not None:
            STATS["bridge"] += 1
        else:
            STATS["fallback"] += 1
            action = _shape(_fallback(obs, cfg), _n_hands(obs))
    except Exception as exc:  # noqa: BLE001
        STATS["reason"] = STATS["reason"] or ("agent: %s" % (exc,))
        action = None
    if action is None:
        action = {"farmer": ["PASS"], "hands": [["PASS"]] * _n_hands(obs), "market": []}
    dt = (time.time() - t0) * 1000.0
    STATS["worst_ms"] = max(STATS["worst_ms"], dt)
    try:
        step = int(obs["step"])
    except Exception:  # noqa: BLE001
        step = 0
    if STATS["turns"] == 1:
        _beacon("start")
    elif step >= 717:
        _beacon("end")
    return action
